/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_chayma_window_suprec (void)
{
  GtkWidget *chayma_window_suprec;
  GtkWidget *fixed25;
  GtkWidget *fixed26;
  GtkWidget *chayma_label_sup;
  GtkWidget *chayma_button_supconf;
  GtkWidget *alignment45;
  GtkWidget *hbox45;
  GtkWidget *image59;
  GtkWidget *label153;
  GtkWidget *chayma_radiobutton_supoui;
  GSList *chayma_radiobutton_supoui_group = NULL;
  GtkWidget *chayma_radiobutton_supnon;

  chayma_window_suprec = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (chayma_window_suprec), _("confirmation suprec"));

  fixed25 = gtk_fixed_new ();
  gtk_widget_show (fixed25);
  gtk_container_add (GTK_CONTAINER (chayma_window_suprec), fixed25);

  fixed26 = gtk_fixed_new ();
  gtk_widget_show (fixed26);
  gtk_fixed_put (GTK_FIXED (fixed25), fixed26, 0, 0);
  gtk_widget_set_size_request (fixed26, 488, 192);

  chayma_label_sup = gtk_label_new (_("ETES-VOUS SUE DE SUPPRIMER CETTE RECLAMATION?"));
  gtk_widget_show (chayma_label_sup);
  gtk_fixed_put (GTK_FIXED (fixed26), chayma_label_sup, 8, 24);
  gtk_widget_set_size_request (chayma_label_sup, 448, 48);

  chayma_button_supconf = gtk_button_new ();
  gtk_widget_show (chayma_button_supconf);
  gtk_fixed_put (GTK_FIXED (fixed26), chayma_button_supconf, 152, 144);
  gtk_widget_set_size_request (chayma_button_supconf, 137, 37);

  alignment45 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment45);
  gtk_container_add (GTK_CONTAINER (chayma_button_supconf), alignment45);

  hbox45 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox45);
  gtk_container_add (GTK_CONTAINER (alignment45), hbox45);

  image59 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image59);
  gtk_box_pack_start (GTK_BOX (hbox45), image59, FALSE, FALSE, 0);

  label153 = gtk_label_new_with_mnemonic (_("   Confirmer "));
  gtk_widget_show (label153);
  gtk_box_pack_start (GTK_BOX (hbox45), label153, FALSE, FALSE, 0);

  chayma_radiobutton_supoui = gtk_radio_button_new_with_mnemonic (NULL, _(" OUI"));
  gtk_widget_show (chayma_radiobutton_supoui);
  gtk_fixed_put (GTK_FIXED (fixed26), chayma_radiobutton_supoui, 104, 96);
  gtk_widget_set_size_request (chayma_radiobutton_supoui, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (chayma_radiobutton_supoui), chayma_radiobutton_supoui_group);
  chayma_radiobutton_supoui_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (chayma_radiobutton_supoui));

  chayma_radiobutton_supnon = gtk_radio_button_new_with_mnemonic (NULL, _("NON"));
  gtk_widget_show (chayma_radiobutton_supnon);
  gtk_fixed_put (GTK_FIXED (fixed26), chayma_radiobutton_supnon, 240, 96);
  gtk_widget_set_size_request (chayma_radiobutton_supnon, 124, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (chayma_radiobutton_supnon), chayma_radiobutton_supoui_group);
  chayma_radiobutton_supoui_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (chayma_radiobutton_supnon));

  g_signal_connect ((gpointer) chayma_button_supconf, "clicked",
                    G_CALLBACK (on_chayma_button_supconf_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_radiobutton_supoui, "toggled",
                    G_CALLBACK (on_chayma_radiobutton_supoui_toggled),
                    NULL);
  g_signal_connect ((gpointer) chayma_radiobutton_supnon, "toggled",
                    G_CALLBACK (on_chayma_radiobutton_supnon_toggled),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (chayma_window_suprec, chayma_window_suprec, "chayma_window_suprec");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, fixed25, "fixed25");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, fixed26, "fixed26");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, chayma_label_sup, "chayma_label_sup");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, chayma_button_supconf, "chayma_button_supconf");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, alignment45, "alignment45");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, hbox45, "hbox45");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, image59, "image59");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, label153, "label153");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, chayma_radiobutton_supoui, "chayma_radiobutton_supoui");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, chayma_radiobutton_supnon, "chayma_radiobutton_supnon");

  return chayma_window_suprec;
}

GtkWidget*
create_modier_reclamation (void)
{
  GtkWidget *modier_reclamation;
  GtkWidget *fixed42;
  GtkWidget *chayma_entry_md_id;
  GtkWidget *chayma_entry_md_le;
  GtkWidget *chayma_entry_md_ob;
  GtkWidget *label252;
  GtkWidget *label255;
  GtkWidget *label256;
  GtkWidget *label257;
  GtkWidget *label258;
  GtkWidget *label259;
  GtkWidget *image114;
  GtkWidget *label253;
  GtkWidget *chayma_textview_md_msg;
  GtkObject *chayma_spinbutton_bv_adj;
  GtkWidget *chayma_spinbutton_bv;
  GtkWidget *chayma_combobox_md_typ;
  GtkWidget *image115;
  GtkWidget *label254;
  GtkWidget *chayma_button_md_re;
  GtkWidget *alignment79;
  GtkWidget *hbox79;
  GtkWidget *image111;
  GtkWidget *label260;
  GtkWidget *chayma_button_md_conf;
  GtkWidget *alignment80;
  GtkWidget *hbox80;
  GtkWidget *image112;
  GtkWidget *label261;
  GtkWidget *chayma_checkbutton_mdf;

  modier_reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modier_reclamation), _("Modifier reclamation"));

  fixed42 = gtk_fixed_new ();
  gtk_widget_show (fixed42);
  gtk_container_add (GTK_CONTAINER (modier_reclamation), fixed42);

  chayma_entry_md_id = gtk_entry_new ();
  gtk_widget_show (chayma_entry_md_id);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_entry_md_id, 368, 136);
  gtk_widget_set_size_request (chayma_entry_md_id, 176, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (chayma_entry_md_id), 8226);

  chayma_entry_md_le = gtk_entry_new ();
  gtk_widget_show (chayma_entry_md_le);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_entry_md_le, 368, 232);
  gtk_widget_set_size_request (chayma_entry_md_le, 176, 24);
  gtk_editable_set_editable (GTK_EDITABLE (chayma_entry_md_le), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (chayma_entry_md_le), 8226);

  chayma_entry_md_ob = gtk_entry_new ();
  gtk_widget_show (chayma_entry_md_ob);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_entry_md_ob, 368, 352);
  gtk_widget_set_size_request (chayma_entry_md_ob, 176, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (chayma_entry_md_ob), 8226);

  label252 = gtk_label_new ("");
  gtk_widget_show (label252);
  gtk_fixed_put (GTK_FIXED (fixed42), label252, 208, 432);
  gtk_widget_set_size_request (label252, 49, 17);

  label255 = gtk_label_new (_("NUMERO DU BUREAU DE VOTE :"));
  gtk_widget_show (label255);
  gtk_fixed_put (GTK_FIXED (fixed42), label255, 64, 176);
  gtk_widget_set_size_request (label255, 256, 41);

  label256 = gtk_label_new (_("LISTE ELECTORALE :"));
  gtk_widget_show (label256);
  gtk_fixed_put (GTK_FIXED (fixed42), label256, 88, 232);
  gtk_widget_set_size_request (label256, 224, 33);

  label257 = gtk_label_new (_("TYPE DE RECLAMATION :"));
  gtk_widget_show (label257);
  gtk_fixed_put (GTK_FIXED (fixed42), label257, 112, 288);
  gtk_widget_set_size_request (label257, 192, 40);

  label258 = gtk_label_new (_("OBJET :"));
  gtk_widget_show (label258);
  gtk_fixed_put (GTK_FIXED (fixed42), label258, 168, 360);
  gtk_widget_set_size_request (label258, 88, 32);

  label259 = gtk_label_new (_("MESSAGE :"));
  gtk_widget_show (label259);
  gtk_fixed_put (GTK_FIXED (fixed42), label259, 152, 400);
  gtk_widget_set_size_request (label259, 112, 24);

  image114 = create_pixmap (modier_reclamation, "index.png");
  gtk_widget_show (image114);
  gtk_fixed_put (GTK_FIXED (fixed42), image114, 0, 0);
  gtk_widget_set_size_request (image114, 184, 136);

  label253 = gtk_label_new (_("MODIFIER RECAMATION"));
  gtk_widget_show (label253);
  gtk_fixed_put (GTK_FIXED (fixed42), label253, 296, 24);
  gtk_widget_set_size_request (label253, 208, 48);

  chayma_textview_md_msg = gtk_text_view_new ();
  gtk_widget_show (chayma_textview_md_msg);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_textview_md_msg, 368, 408);
  gtk_widget_set_size_request (chayma_textview_md_msg, 200, 96);

  chayma_spinbutton_bv_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  chayma_spinbutton_bv = gtk_spin_button_new (GTK_ADJUSTMENT (chayma_spinbutton_bv_adj), 1, 0);
  gtk_widget_show (chayma_spinbutton_bv);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_spinbutton_bv, 368, 184);
  gtk_widget_set_size_request (chayma_spinbutton_bv, 60, 27);

  chayma_combobox_md_typ = gtk_combo_box_new_text ();
  gtk_widget_show (chayma_combobox_md_typ);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_combobox_md_typ, 368, 288);
  gtk_widget_set_size_request (chayma_combobox_md_typ, 182, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (chayma_combobox_md_typ), _("1-pratique "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (chayma_combobox_md_typ), _("2-theorique"));

  image115 = create_pixmap (modier_reclamation, "images.png");
  gtk_widget_show (image115);
  gtk_fixed_put (GTK_FIXED (fixed42), image115, 584, 80);
  gtk_widget_set_size_request (image115, 232, 256);

  label254 = gtk_label_new (_("VOTRE ID :"));
  gtk_widget_show (label254);
  gtk_fixed_put (GTK_FIXED (fixed42), label254, 160, 136);
  gtk_widget_set_size_request (label254, 88, 33);

  chayma_button_md_re = gtk_button_new ();
  gtk_widget_show (chayma_button_md_re);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_button_md_re, 56, 552);
  gtk_widget_set_size_request (chayma_button_md_re, 160, 48);

  alignment79 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment79);
  gtk_container_add (GTK_CONTAINER (chayma_button_md_re), alignment79);

  hbox79 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox79);
  gtk_container_add (GTK_CONTAINER (alignment79), hbox79);

  image111 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image111);
  gtk_box_pack_start (GTK_BOX (hbox79), image111, FALSE, FALSE, 0);

  label260 = gtk_label_new_with_mnemonic (_(" Retour"));
  gtk_widget_show (label260);
  gtk_box_pack_start (GTK_BOX (hbox79), label260, FALSE, FALSE, 0);

  chayma_button_md_conf = gtk_button_new ();
  gtk_widget_show (chayma_button_md_conf);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_button_md_conf, 624, 544);
  gtk_widget_set_size_request (chayma_button_md_conf, 176, 48);

  alignment80 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment80);
  gtk_container_add (GTK_CONTAINER (chayma_button_md_conf), alignment80);

  hbox80 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox80);
  gtk_container_add (GTK_CONTAINER (alignment80), hbox80);

  image112 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image112);
  gtk_box_pack_start (GTK_BOX (hbox80), image112, FALSE, FALSE, 0);

  label261 = gtk_label_new_with_mnemonic (_(" Confirmer"));
  gtk_widget_show (label261);
  gtk_box_pack_start (GTK_BOX (hbox80), label261, FALSE, FALSE, 0);

  chayma_checkbutton_mdf = gtk_check_button_new_with_mnemonic (_(" I'm not Robot"));
  gtk_widget_show (chayma_checkbutton_mdf);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_checkbutton_mdf, 368, 544);
  gtk_widget_set_size_request (chayma_checkbutton_mdf, 144, 24);

  g_signal_connect ((gpointer) chayma_button_md_re, "clicked",
                    G_CALLBACK (on_chayma_button_md_ret_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_md_conf, "clicked",
                    G_CALLBACK (on_chayma_button_md_conf_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_checkbutton_mdf, "activate",
                    G_CALLBACK (on_chayma_checkbutton_mdf_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modier_reclamation, modier_reclamation, "modier_reclamation");
  GLADE_HOOKUP_OBJECT (modier_reclamation, fixed42, "fixed42");
  GLADE_HOOKUP_OBJECT (modier_reclamation, chayma_entry_md_id, "chayma_entry_md_id");
  GLADE_HOOKUP_OBJECT (modier_reclamation, chayma_entry_md_le, "chayma_entry_md_le");
  GLADE_HOOKUP_OBJECT (modier_reclamation, chayma_entry_md_ob, "chayma_entry_md_ob");
  GLADE_HOOKUP_OBJECT (modier_reclamation, label252, "label252");
  GLADE_HOOKUP_OBJECT (modier_reclamation, label255, "label255");
  GLADE_HOOKUP_OBJECT (modier_reclamation, label256, "label256");
  GLADE_HOOKUP_OBJECT (modier_reclamation, label257, "label257");
  GLADE_HOOKUP_OBJECT (modier_reclamation, label258, "label258");
  GLADE_HOOKUP_OBJECT (modier_reclamation, label259, "label259");
  GLADE_HOOKUP_OBJECT (modier_reclamation, image114, "image114");
  GLADE_HOOKUP_OBJECT (modier_reclamation, label253, "label253");
  GLADE_HOOKUP_OBJECT (modier_reclamation, chayma_textview_md_msg, "chayma_textview_md_msg");
  GLADE_HOOKUP_OBJECT (modier_reclamation, chayma_spinbutton_bv, "chayma_spinbutton_bv");
  GLADE_HOOKUP_OBJECT (modier_reclamation, chayma_combobox_md_typ, "chayma_combobox_md_typ");
  GLADE_HOOKUP_OBJECT (modier_reclamation, image115, "image115");
  GLADE_HOOKUP_OBJECT (modier_reclamation, label254, "label254");
  GLADE_HOOKUP_OBJECT (modier_reclamation, chayma_button_md_re, "chayma_button_md_re");
  GLADE_HOOKUP_OBJECT (modier_reclamation, alignment79, "alignment79");
  GLADE_HOOKUP_OBJECT (modier_reclamation, hbox79, "hbox79");
  GLADE_HOOKUP_OBJECT (modier_reclamation, image111, "image111");
  GLADE_HOOKUP_OBJECT (modier_reclamation, label260, "label260");
  GLADE_HOOKUP_OBJECT (modier_reclamation, chayma_button_md_conf, "chayma_button_md_conf");
  GLADE_HOOKUP_OBJECT (modier_reclamation, alignment80, "alignment80");
  GLADE_HOOKUP_OBJECT (modier_reclamation, hbox80, "hbox80");
  GLADE_HOOKUP_OBJECT (modier_reclamation, image112, "image112");
  GLADE_HOOKUP_OBJECT (modier_reclamation, label261, "label261");
  GLADE_HOOKUP_OBJECT (modier_reclamation, chayma_checkbutton_mdf, "chayma_checkbutton_mdf");

  return modier_reclamation;
}

GtkWidget*
create_Liste_reclamation (void)
{
  GtkWidget *Liste_reclamation;
  GtkWidget *fixed48;
  GtkWidget *chayma_treeview_ls;
  GtkWidget *chayma_entry_ls_numlist;
  GtkWidget *label300;
  GtkWidget *label297;
  GtkWidget *label302;
  GtkWidget *image146;
  GtkWidget *chayma_button_ls_actualiser;
  GtkWidget *alignment106;
  GtkWidget *hbox106;
  GtkWidget *image159;
  GtkWidget *label318;
  GtkWidget *chayma_button_ls_recherche;
  GtkWidget *alignment102;
  GtkWidget *hbox102;
  GtkWidget *image147;
  GtkWidget *label301;
  GtkWidget *chayma_radiobutton_ls_NumBV;
  GSList *chayma_radiobutton_ls_NumBV_group = NULL;
  GtkWidget *chayma_radiobutton_ls_obj;
  GSList *chayma_radiobutton_ls_obj_group = NULL;
  GtkWidget *chayma_radiobutton_ls_type;
  GSList *chayma_radiobutton_ls_type_group = NULL;
  GtkWidget *chayma_button_ls_ajout;
  GtkWidget *alignment97;
  GtkWidget *hbox97;
  GtkWidget *image141;
  GtkWidget *label294;
  GtkWidget *chayma_button_ls_mdf;
  GtkWidget *alignment98;
  GtkWidget *hbox98;
  GtkWidget *image142;
  GtkWidget *label295;
  GtkWidget *chayma_button_ls_sup;
  GtkWidget *alignment99;
  GtkWidget *hbox99;
  GtkWidget *image143;
  GtkWidget *label296;
  GtkWidget *chayma_button_ls_dec;
  GtkWidget *alignment96;
  GtkWidget *hbox96;
  GtkWidget *image140;
  GtkWidget *label293;
  GtkWidget *chayma_button_stat_gag;
  GtkWidget *alignment100;
  GtkWidget *hbox100;
  GtkWidget *image144;
  GtkWidget *label298;
  GtkWidget *chayma_button_stat_rec;
  GtkWidget *alignment101;
  GtkWidget *hbox101;
  GtkWidget *image145;
  GtkWidget *label299;

  Liste_reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Liste_reclamation), _("Liste reclamation"));

  fixed48 = gtk_fixed_new ();
  gtk_widget_show (fixed48);
  gtk_container_add (GTK_CONTAINER (Liste_reclamation), fixed48);
  gtk_widget_set_size_request (fixed48, 0, 0);

  chayma_treeview_ls = gtk_tree_view_new ();
  gtk_widget_show (chayma_treeview_ls);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_treeview_ls, 96, 144);
  gtk_widget_set_size_request (chayma_treeview_ls, 384, 312);

  chayma_entry_ls_numlist = gtk_entry_new ();
  gtk_widget_show (chayma_entry_ls_numlist);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_entry_ls_numlist, 688, 168);
  gtk_widget_set_size_request (chayma_entry_ls_numlist, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (chayma_entry_ls_numlist), 8226);

  label300 = gtk_label_new (_("LISTE RECLAMATION"));
  gtk_widget_show (label300);
  gtk_fixed_put (GTK_FIXED (fixed48), label300, 368, 8);
  gtk_widget_set_size_request (label300, 216, 33);

  label297 = gtk_label_new ("");
  gtk_widget_show (label297);
  gtk_fixed_put (GTK_FIXED (fixed48), label297, 272, 576);
  gtk_widget_set_size_request (label297, 376, 64);

  label302 = gtk_label_new (_("Num liste electorale"));
  gtk_widget_show (label302);
  gtk_fixed_put (GTK_FIXED (fixed48), label302, 688, 120);
  gtk_widget_set_size_request (label302, 161, 24);

  image146 = create_pixmap (Liste_reclamation, "index.png");
  gtk_widget_show (image146);
  gtk_fixed_put (GTK_FIXED (fixed48), image146, 0, 0);
  gtk_widget_set_size_request (image146, 184, 136);

  chayma_button_ls_actualiser = gtk_button_new ();
  gtk_widget_show (chayma_button_ls_actualiser);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_ls_actualiser, 224, 88);
  gtk_widget_set_size_request (chayma_button_ls_actualiser, 112, 40);

  alignment106 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment106);
  gtk_container_add (GTK_CONTAINER (chayma_button_ls_actualiser), alignment106);

  hbox106 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox106);
  gtk_container_add (GTK_CONTAINER (alignment106), hbox106);

  image159 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image159);
  gtk_box_pack_start (GTK_BOX (hbox106), image159, FALSE, FALSE, 0);

  label318 = gtk_label_new_with_mnemonic (_("  Actualiser"));
  gtk_widget_show (label318);
  gtk_box_pack_start (GTK_BOX (hbox106), label318, FALSE, FALSE, 0);

  chayma_button_ls_recherche = gtk_button_new ();
  gtk_widget_show (chayma_button_ls_recherche);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_ls_recherche, 552, 168);
  gtk_widget_set_size_request (chayma_button_ls_recherche, 120, 32);

  alignment102 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment102);
  gtk_container_add (GTK_CONTAINER (chayma_button_ls_recherche), alignment102);

  hbox102 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox102);
  gtk_container_add (GTK_CONTAINER (alignment102), hbox102);

  image147 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image147);
  gtk_box_pack_start (GTK_BOX (hbox102), image147, FALSE, FALSE, 0);

  label301 = gtk_label_new_with_mnemonic (_("  Recherche"));
  gtk_widget_show (label301);
  gtk_box_pack_start (GTK_BOX (hbox102), label301, FALSE, FALSE, 0);

  chayma_radiobutton_ls_NumBV = gtk_radio_button_new_with_mnemonic (NULL, _("Num Bureau de vote"));
  gtk_widget_show (chayma_radiobutton_ls_NumBV);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_radiobutton_ls_NumBV, 568, 232);
  gtk_widget_set_size_request (chayma_radiobutton_ls_NumBV, 200, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (chayma_radiobutton_ls_NumBV), chayma_radiobutton_ls_NumBV_group);
  chayma_radiobutton_ls_NumBV_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (chayma_radiobutton_ls_NumBV));

  chayma_radiobutton_ls_obj = gtk_radio_button_new_with_mnemonic (NULL, _("objet"));
  gtk_widget_show (chayma_radiobutton_ls_obj);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_radiobutton_ls_obj, 568, 272);
  gtk_widget_set_size_request (chayma_radiobutton_ls_obj, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (chayma_radiobutton_ls_obj), chayma_radiobutton_ls_obj_group);
  chayma_radiobutton_ls_obj_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (chayma_radiobutton_ls_obj));

  chayma_radiobutton_ls_type = gtk_radio_button_new_with_mnemonic (NULL, _("type"));
  gtk_widget_show (chayma_radiobutton_ls_type);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_radiobutton_ls_type, 568, 312);
  gtk_widget_set_size_request (chayma_radiobutton_ls_type, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (chayma_radiobutton_ls_type), chayma_radiobutton_ls_type_group);
  chayma_radiobutton_ls_type_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (chayma_radiobutton_ls_type));

  chayma_button_ls_ajout = gtk_button_new ();
  gtk_widget_show (chayma_button_ls_ajout);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_ls_ajout, 104, 504);
  gtk_widget_set_size_request (chayma_button_ls_ajout, 168, 48);

  alignment97 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment97);
  gtk_container_add (GTK_CONTAINER (chayma_button_ls_ajout), alignment97);

  hbox97 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox97);
  gtk_container_add (GTK_CONTAINER (alignment97), hbox97);

  image141 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image141);
  gtk_box_pack_start (GTK_BOX (hbox97), image141, FALSE, FALSE, 0);

  label294 = gtk_label_new_with_mnemonic (_(" Ajouter"));
  gtk_widget_show (label294);
  gtk_box_pack_start (GTK_BOX (hbox97), label294, FALSE, FALSE, 0);

  chayma_button_ls_mdf = gtk_button_new ();
  gtk_widget_show (chayma_button_ls_mdf);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_ls_mdf, 288, 504);
  gtk_widget_set_size_request (chayma_button_ls_mdf, 168, 48);

  alignment98 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment98);
  gtk_container_add (GTK_CONTAINER (chayma_button_ls_mdf), alignment98);

  hbox98 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox98);
  gtk_container_add (GTK_CONTAINER (alignment98), hbox98);

  image142 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image142);
  gtk_box_pack_start (GTK_BOX (hbox98), image142, FALSE, FALSE, 0);

  label295 = gtk_label_new_with_mnemonic (_(" Modifier"));
  gtk_widget_show (label295);
  gtk_box_pack_start (GTK_BOX (hbox98), label295, FALSE, FALSE, 0);

  chayma_button_ls_sup = gtk_button_new ();
  gtk_widget_show (chayma_button_ls_sup);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_ls_sup, 464, 504);
  gtk_widget_set_size_request (chayma_button_ls_sup, 168, 48);

  alignment99 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment99);
  gtk_container_add (GTK_CONTAINER (chayma_button_ls_sup), alignment99);

  hbox99 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox99);
  gtk_container_add (GTK_CONTAINER (alignment99), hbox99);

  image143 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image143);
  gtk_box_pack_start (GTK_BOX (hbox99), image143, FALSE, FALSE, 0);

  label296 = gtk_label_new_with_mnemonic (_("  Supprimer"));
  gtk_widget_show (label296);
  gtk_box_pack_start (GTK_BOX (hbox99), label296, FALSE, FALSE, 0);

  chayma_button_ls_dec = gtk_button_new ();
  gtk_widget_show (chayma_button_ls_dec);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_ls_dec, 40, 576);
  gtk_widget_set_size_request (chayma_button_ls_dec, 144, 40);

  alignment96 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment96);
  gtk_container_add (GTK_CONTAINER (chayma_button_ls_dec), alignment96);

  hbox96 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox96);
  gtk_container_add (GTK_CONTAINER (alignment96), hbox96);

  image140 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image140);
  gtk_box_pack_start (GTK_BOX (hbox96), image140, FALSE, FALSE, 0);

  label293 = gtk_label_new_with_mnemonic (_(" D\303\251connecter"));
  gtk_widget_show (label293);
  gtk_box_pack_start (GTK_BOX (hbox96), label293, FALSE, FALSE, 0);

  chayma_button_stat_gag = gtk_button_new ();
  gtk_widget_show (chayma_button_stat_gag);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_stat_gag, 752, 504);
  gtk_widget_set_size_request (chayma_button_stat_gag, 152, 48);

  alignment100 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment100);
  gtk_container_add (GTK_CONTAINER (chayma_button_stat_gag), alignment100);

  hbox100 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox100);
  gtk_container_add (GTK_CONTAINER (alignment100), hbox100);

  image144 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image144);
  gtk_box_pack_start (GTK_BOX (hbox100), image144, FALSE, FALSE, 0);

  label298 = gtk_label_new_with_mnemonic (_("   Les conseiller \n         gagnant"));
  gtk_widget_show (label298);
  gtk_box_pack_start (GTK_BOX (hbox100), label298, FALSE, FALSE, 0);

  chayma_button_stat_rec = gtk_button_new ();
  gtk_widget_show (chayma_button_stat_rec);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_stat_rec, 752, 568);
  gtk_widget_set_size_request (chayma_button_stat_rec, 152, 72);

  alignment101 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment101);
  gtk_container_add (GTK_CONTAINER (chayma_button_stat_rec), alignment101);

  hbox101 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox101);
  gtk_container_add (GTK_CONTAINER (alignment101), hbox101);

  image145 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image145);
  gtk_box_pack_start (GTK_BOX (hbox101), image145, FALSE, FALSE, 0);

  label299 = gtk_label_new_with_mnemonic (_("   Nombre de \n   reclamation \n    par liste"));
  gtk_widget_show (label299);
  gtk_box_pack_start (GTK_BOX (hbox101), label299, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) chayma_treeview_ls, "row_activated",
                    G_CALLBACK (on_chayma_treeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_ls_actualiser, "clicked",
                    G_CALLBACK (on_chayma_button_ls_actualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_ls_recherche, "clicked",
                    G_CALLBACK (on_chayma_button_ls_recherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_radiobutton_ls_NumBV, "toggled",
                    G_CALLBACK (on_chayma_radiobutton_ls_NumBV_toggled),
                    NULL);
  g_signal_connect ((gpointer) chayma_radiobutton_ls_obj, "toggled",
                    G_CALLBACK (on_chayma_radiobutton_ls_obj_toggled),
                    NULL);
  g_signal_connect ((gpointer) chayma_radiobutton_ls_type, "toggled",
                    G_CALLBACK (on_chayma_radiobutton_ls_type_toggled),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_ls_ajout, "clicked",
                    G_CALLBACK (on_chayma_button_ls_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_ls_mdf, "clicked",
                    G_CALLBACK (on_chayma_button_ls_mdf_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_ls_sup, "clicked",
                    G_CALLBACK (on_chayma_button_ls_sup_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_ls_dec, "clicked",
                    G_CALLBACK (on_chayma_button_ls_dec_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_stat_gag, "clicked",
                    G_CALLBACK (on_chayma_button_stat_gag_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_stat_rec, "clicked",
                    G_CALLBACK (on_chayma_button_stat_rec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Liste_reclamation, Liste_reclamation, "Liste_reclamation");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, fixed48, "fixed48");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_treeview_ls, "chayma_treeview_ls");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_entry_ls_numlist, "chayma_entry_ls_numlist");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label300, "label300");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label297, "label297");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label302, "label302");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image146, "image146");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_ls_actualiser, "chayma_button_ls_actualiser");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment106, "alignment106");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox106, "hbox106");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image159, "image159");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label318, "label318");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_ls_recherche, "chayma_button_ls_recherche");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment102, "alignment102");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox102, "hbox102");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image147, "image147");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label301, "label301");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_radiobutton_ls_NumBV, "chayma_radiobutton_ls_NumBV");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_radiobutton_ls_obj, "chayma_radiobutton_ls_obj");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_radiobutton_ls_type, "chayma_radiobutton_ls_type");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_ls_ajout, "chayma_button_ls_ajout");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment97, "alignment97");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox97, "hbox97");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image141, "image141");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label294, "label294");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_ls_mdf, "chayma_button_ls_mdf");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment98, "alignment98");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox98, "hbox98");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image142, "image142");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label295, "label295");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_ls_sup, "chayma_button_ls_sup");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment99, "alignment99");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox99, "hbox99");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image143, "image143");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label296, "label296");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_ls_dec, "chayma_button_ls_dec");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment96, "alignment96");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox96, "hbox96");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image140, "image140");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label293, "label293");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_stat_gag, "chayma_button_stat_gag");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment100, "alignment100");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox100, "hbox100");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image144, "image144");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label298, "label298");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_stat_rec, "chayma_button_stat_rec");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment101, "alignment101");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox101, "hbox101");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image145, "image145");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label299, "label299");

  return Liste_reclamation;
}

GtkWidget*
create_choix_de_gestion (void)
{
  GtkWidget *choix_de_gestion;
  GtkWidget *fixed49;
  GtkWidget *image148;
  GtkWidget *image150;
  GtkWidget *button88;
  GtkWidget *button89;
  GtkWidget *button90;
  GtkWidget *image151;
  GtkWidget *image152;
  GtkWidget *image149;
  GtkWidget *button92;
  GtkWidget *chayma_button_espace_reclamation;

  choix_de_gestion = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (choix_de_gestion), _("choix de gestion"));

  fixed49 = gtk_fixed_new ();
  gtk_widget_show (fixed49);
  gtk_container_add (GTK_CONTAINER (choix_de_gestion), fixed49);

  image148 = create_pixmap (choix_de_gestion, "Capture d’écran 2022-11-15 112246.png");
  gtk_widget_show (image148);
  gtk_fixed_put (GTK_FIXED (fixed49), image148, 360, 184);
  gtk_widget_set_size_request (image148, 184, 152);

  image150 = create_pixmap (choix_de_gestion, "Capture d’écran 2022-11-15 112309.png");
  gtk_widget_show (image150);
  gtk_fixed_put (GTK_FIXED (fixed49), image150, 80, 392);
  gtk_widget_set_size_request (image150, 192, 152);

  button88 = gtk_button_new_with_mnemonic (_("ESPACE ELECTIONS"));
  gtk_widget_show (button88);
  gtk_fixed_put (GTK_FIXED (fixed49), button88, 64, 192);
  gtk_widget_set_size_request (button88, 200, 30);

  button89 = gtk_button_new_with_mnemonic (_("ESPACE ADMIN"));
  gtk_widget_show (button89);
  gtk_fixed_put (GTK_FIXED (fixed49), button89, 632, 176);
  gtk_widget_set_size_request (button89, 200, 30);

  button90 = gtk_button_new_with_mnemonic (_("ESPACE VOTE"));
  gtk_widget_show (button90);
  gtk_fixed_put (GTK_FIXED (fixed49), button90, 624, 552);
  gtk_widget_set_size_request (button90, 200, 30);

  image151 = create_pixmap (choix_de_gestion, "Capture d’écran 2022-11-15 112254.png");
  gtk_widget_show (image151);
  gtk_fixed_put (GTK_FIXED (fixed49), image151, 624, 16);
  gtk_widget_set_size_request (image151, 216, 168);

  image152 = create_pixmap (choix_de_gestion, "Capture d’écran 2022-11-15 112235.png");
  gtk_widget_show (image152);
  gtk_fixed_put (GTK_FIXED (fixed49), image152, 64, 24);
  gtk_widget_set_size_request (image152, 200, 160);

  image149 = create_pixmap (choix_de_gestion, "Capture d’écran 2022-11-15 112318.png");
  gtk_widget_show (image149);
  gtk_fixed_put (GTK_FIXED (fixed49), image149, 616, 392);
  gtk_widget_set_size_request (image149, 232, 152);

  button92 = gtk_button_new_with_mnemonic (_("ESPACE BUREAU DE VOTE"));
  gtk_widget_show (button92);
  gtk_fixed_put (GTK_FIXED (fixed49), button92, 344, 344);
  gtk_widget_set_size_request (button92, 200, 30);

  chayma_button_espace_reclamation = gtk_button_new_with_mnemonic (_("ESPACE RECLAMATION"));
  gtk_widget_show (chayma_button_espace_reclamation);
  gtk_fixed_put (GTK_FIXED (fixed49), chayma_button_espace_reclamation, 80, 536);
  gtk_widget_set_size_request (chayma_button_espace_reclamation, 200, 30);

  g_signal_connect ((gpointer) button88, "clicked",
                    G_CALLBACK (on_button_Esp_Elec_clicked),
                    NULL);
  g_signal_connect ((gpointer) button89, "clicked",
                    G_CALLBACK (on_button_Esp_Admin_clicked),
                    NULL);
  g_signal_connect ((gpointer) button90, "clicked",
                    G_CALLBACK (on_button_Esp_Vote_clicked),
                    NULL);
  g_signal_connect ((gpointer) button92, "clicked",
                    G_CALLBACK (on_button_Esp_BV_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_espace_reclamation, "clicked",
                    G_CALLBACK (on_chayma_button_espace_reclamation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (choix_de_gestion, choix_de_gestion, "choix_de_gestion");
  GLADE_HOOKUP_OBJECT (choix_de_gestion, fixed49, "fixed49");
  GLADE_HOOKUP_OBJECT (choix_de_gestion, image148, "image148");
  GLADE_HOOKUP_OBJECT (choix_de_gestion, image150, "image150");
  GLADE_HOOKUP_OBJECT (choix_de_gestion, button88, "button88");
  GLADE_HOOKUP_OBJECT (choix_de_gestion, button89, "button89");
  GLADE_HOOKUP_OBJECT (choix_de_gestion, button90, "button90");
  GLADE_HOOKUP_OBJECT (choix_de_gestion, image151, "image151");
  GLADE_HOOKUP_OBJECT (choix_de_gestion, image152, "image152");
  GLADE_HOOKUP_OBJECT (choix_de_gestion, image149, "image149");
  GLADE_HOOKUP_OBJECT (choix_de_gestion, button92, "button92");
  GLADE_HOOKUP_OBJECT (choix_de_gestion, chayma_button_espace_reclamation, "chayma_button_espace_reclamation");

  return choix_de_gestion;
}

GtkWidget*
create_Log_in (void)
{
  GtkWidget *Log_in;
  GtkWidget *fixed50;
  GtkWidget *reclamation_entry_log_id;
  GtkWidget *reclamation_entry_log_mdp;
  GtkWidget *label303;
  GtkWidget *label304;
  GtkWidget *label305;
  GtkWidget *label307;
  GtkWidget *image154;
  GtkWidget *reclamation_button_con;
  GtkWidget *alignment103;
  GtkWidget *hbox103;
  GtkWidget *image153;
  GtkWidget *label306;

  Log_in = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Log_in), _("Log in"));

  fixed50 = gtk_fixed_new ();
  gtk_widget_show (fixed50);
  gtk_container_add (GTK_CONTAINER (Log_in), fixed50);

  reclamation_entry_log_id = gtk_entry_new ();
  gtk_widget_show (reclamation_entry_log_id);
  gtk_fixed_put (GTK_FIXED (fixed50), reclamation_entry_log_id, 216, 168);
  gtk_widget_set_size_request (reclamation_entry_log_id, 250, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (reclamation_entry_log_id), 8226);

  reclamation_entry_log_mdp = gtk_entry_new ();
  gtk_widget_show (reclamation_entry_log_mdp);
  gtk_fixed_put (GTK_FIXED (fixed50), reclamation_entry_log_mdp, 216, 232);
  gtk_widget_set_size_request (reclamation_entry_log_mdp, 250, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (reclamation_entry_log_mdp), 8226);

  label303 = gtk_label_new (_("CONNECTION:"));
  gtk_widget_show (label303);
  gtk_fixed_put (GTK_FIXED (fixed50), label303, 176, 88);
  gtk_widget_set_size_request (label303, 304, 40);

  label304 = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label304);
  gtk_fixed_put (GTK_FIXED (fixed50), label304, 40, 168);
  gtk_widget_set_size_request (label304, 176, 40);

  label305 = gtk_label_new (_("Mot de passe :"));
  gtk_widget_show (label305);
  gtk_fixed_put (GTK_FIXED (fixed50), label305, 48, 232);
  gtk_widget_set_size_request (label305, 160, 32);

  label307 = gtk_label_new ("");
  gtk_widget_show (label307);
  gtk_fixed_put (GTK_FIXED (fixed50), label307, 184, 376);
  gtk_widget_set_size_request (label307, 288, 40);

  image154 = create_pixmap (Log_in, "index.png");
  gtk_widget_show (image154);
  gtk_fixed_put (GTK_FIXED (fixed50), image154, 0, 0);
  gtk_widget_set_size_request (image154, 176, 128);

  reclamation_button_con = gtk_button_new ();
  gtk_widget_show (reclamation_button_con);
  gtk_fixed_put (GTK_FIXED (fixed50), reclamation_button_con, 264, 296);
  gtk_widget_set_size_request (reclamation_button_con, 143, 38);

  alignment103 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment103);
  gtk_container_add (GTK_CONTAINER (reclamation_button_con), alignment103);

  hbox103 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox103);
  gtk_container_add (GTK_CONTAINER (alignment103), hbox103);

  image153 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image153);
  gtk_box_pack_start (GTK_BOX (hbox103), image153, FALSE, FALSE, 0);

  label306 = gtk_label_new_with_mnemonic (_("    CONNECTER "));
  gtk_widget_show (label306);
  gtk_box_pack_start (GTK_BOX (hbox103), label306, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) reclamation_button_con, "clicked",
                    G_CALLBACK (on_reclamation_button_con_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Log_in, Log_in, "Log_in");
  GLADE_HOOKUP_OBJECT (Log_in, fixed50, "fixed50");
  GLADE_HOOKUP_OBJECT (Log_in, reclamation_entry_log_id, "reclamation_entry_log_id");
  GLADE_HOOKUP_OBJECT (Log_in, reclamation_entry_log_mdp, "reclamation_entry_log_mdp");
  GLADE_HOOKUP_OBJECT (Log_in, label303, "label303");
  GLADE_HOOKUP_OBJECT (Log_in, label304, "label304");
  GLADE_HOOKUP_OBJECT (Log_in, label305, "label305");
  GLADE_HOOKUP_OBJECT (Log_in, label307, "label307");
  GLADE_HOOKUP_OBJECT (Log_in, image154, "image154");
  GLADE_HOOKUP_OBJECT (Log_in, reclamation_button_con, "reclamation_button_con");
  GLADE_HOOKUP_OBJECT (Log_in, alignment103, "alignment103");
  GLADE_HOOKUP_OBJECT (Log_in, hbox103, "hbox103");
  GLADE_HOOKUP_OBJECT (Log_in, image153, "image153");
  GLADE_HOOKUP_OBJECT (Log_in, label306, "label306");

  return Log_in;
}

GtkWidget*
create_ajouter_reclamation (void)
{
  GtkWidget *ajouter_reclamation;
  GtkWidget *fixed51;
  GtkWidget *chayma_entry_aj_id;
  GtkWidget *chayma_entry_aj_listelec;
  GtkWidget *chayma_entry_aj_obj;
  GtkWidget *label308;
  GtkWidget *label310;
  GtkWidget *label311;
  GtkWidget *label312;
  GtkWidget *label313;
  GtkWidget *label314;
  GtkWidget *label315;
  GtkWidget *chayma_textview_aj_msg;
  GtkObject *chayma_spinbutton_aj_NumBV_adj;
  GtkWidget *chayma_spinbutton_aj_NumBV;
  GtkWidget *label309;
  GtkWidget *chayma_combobox_aj_type;
  GtkWidget *image155;
  GtkWidget *image157;
  GtkWidget *chayma_button_aj_ret;
  GtkWidget *alignment105;
  GtkWidget *hbox105;
  GtkWidget *image158;
  GtkWidget *label317;
  GtkWidget *chayma_button_aj_conf;
  GtkWidget *alignment104;
  GtkWidget *hbox104;
  GtkWidget *image156;
  GtkWidget *label316;
  GtkWidget *chayma_checkbutton_aj;

  ajouter_reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_reclamation), _("Ajouter reclamation"));

  fixed51 = gtk_fixed_new ();
  gtk_widget_show (fixed51);
  gtk_container_add (GTK_CONTAINER (ajouter_reclamation), fixed51);

  chayma_entry_aj_id = gtk_entry_new ();
  gtk_widget_show (chayma_entry_aj_id);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_entry_aj_id, 352, 136);
  gtk_widget_set_size_request (chayma_entry_aj_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (chayma_entry_aj_id), 8226);

  chayma_entry_aj_listelec = gtk_entry_new ();
  gtk_widget_show (chayma_entry_aj_listelec);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_entry_aj_listelec, 352, 240);
  gtk_widget_set_size_request (chayma_entry_aj_listelec, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (chayma_entry_aj_listelec), 8226);

  chayma_entry_aj_obj = gtk_entry_new ();
  gtk_widget_show (chayma_entry_aj_obj);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_entry_aj_obj, 352, 360);
  gtk_widget_set_size_request (chayma_entry_aj_obj, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (chayma_entry_aj_obj), 8226);

  label308 = gtk_label_new ("");
  gtk_widget_show (label308);
  gtk_fixed_put (GTK_FIXED (fixed51), label308, 208, 432);
  gtk_widget_set_size_request (label308, 49, 17);

  label310 = gtk_label_new (_("NUMERO DU BUREAU DE VOTE :"));
  gtk_widget_show (label310);
  gtk_fixed_put (GTK_FIXED (fixed51), label310, 64, 176);
  gtk_widget_set_size_request (label310, 256, 41);

  label311 = gtk_label_new (_("LISTE ELECTORALE :"));
  gtk_widget_show (label311);
  gtk_fixed_put (GTK_FIXED (fixed51), label311, 88, 232);
  gtk_widget_set_size_request (label311, 224, 33);

  label312 = gtk_label_new (_("TYPE DE RECLAMATION :"));
  gtk_widget_show (label312);
  gtk_fixed_put (GTK_FIXED (fixed51), label312, 112, 288);
  gtk_widget_set_size_request (label312, 192, 40);

  label313 = gtk_label_new (_("OBJET :"));
  gtk_widget_show (label313);
  gtk_fixed_put (GTK_FIXED (fixed51), label313, 168, 360);
  gtk_widget_set_size_request (label313, 88, 32);

  label314 = gtk_label_new (_("MESSAGE :"));
  gtk_widget_show (label314);
  gtk_fixed_put (GTK_FIXED (fixed51), label314, 152, 400);
  gtk_widget_set_size_request (label314, 112, 24);

  label315 = gtk_label_new (_("AJOUTER RECAMATION"));
  gtk_widget_show (label315);
  gtk_fixed_put (GTK_FIXED (fixed51), label315, 344, 32);
  gtk_widget_set_size_request (label315, 208, 48);

  chayma_textview_aj_msg = gtk_text_view_new ();
  gtk_widget_show (chayma_textview_aj_msg);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_textview_aj_msg, 352, 400);
  gtk_widget_set_size_request (chayma_textview_aj_msg, 200, 96);

  chayma_spinbutton_aj_NumBV_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  chayma_spinbutton_aj_NumBV = gtk_spin_button_new (GTK_ADJUSTMENT (chayma_spinbutton_aj_NumBV_adj), 1, 0);
  gtk_widget_show (chayma_spinbutton_aj_NumBV);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_spinbutton_aj_NumBV, 352, 184);
  gtk_widget_set_size_request (chayma_spinbutton_aj_NumBV, 60, 27);

  label309 = gtk_label_new (_("VOTRE ID :"));
  gtk_widget_show (label309);
  gtk_fixed_put (GTK_FIXED (fixed51), label309, 144, 128);
  gtk_widget_set_size_request (label309, 88, 33);

  chayma_combobox_aj_type = gtk_combo_box_new_text ();
  gtk_widget_show (chayma_combobox_aj_type);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_combobox_aj_type, 352, 296);
  gtk_widget_set_size_request (chayma_combobox_aj_type, 182, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (chayma_combobox_aj_type), _("pratique "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (chayma_combobox_aj_type), _("theorique"));

  image155 = create_pixmap (ajouter_reclamation, "images.png");
  gtk_widget_show (image155);
  gtk_fixed_put (GTK_FIXED (fixed51), image155, 608, 88);
  gtk_widget_set_size_request (image155, 232, 256);

  image157 = create_pixmap (ajouter_reclamation, "index.png");
  gtk_widget_show (image157);
  gtk_fixed_put (GTK_FIXED (fixed51), image157, 0, 0);
  gtk_widget_set_size_request (image157, 184, 136);

  chayma_button_aj_ret = gtk_button_new ();
  gtk_widget_show (chayma_button_aj_ret);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_button_aj_ret, 32, 552);
  gtk_widget_set_size_request (chayma_button_aj_ret, 168, 48);

  alignment105 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment105);
  gtk_container_add (GTK_CONTAINER (chayma_button_aj_ret), alignment105);

  hbox105 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox105);
  gtk_container_add (GTK_CONTAINER (alignment105), hbox105);

  image158 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image158);
  gtk_box_pack_start (GTK_BOX (hbox105), image158, FALSE, FALSE, 0);

  label317 = gtk_label_new_with_mnemonic (_(" Retour"));
  gtk_widget_show (label317);
  gtk_box_pack_start (GTK_BOX (hbox105), label317, FALSE, FALSE, 0);

  chayma_button_aj_conf = gtk_button_new ();
  gtk_widget_show (chayma_button_aj_conf);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_button_aj_conf, 704, 544);
  gtk_widget_set_size_request (chayma_button_aj_conf, 192, 56);

  alignment104 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment104);
  gtk_container_add (GTK_CONTAINER (chayma_button_aj_conf), alignment104);

  hbox104 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox104);
  gtk_container_add (GTK_CONTAINER (alignment104), hbox104);

  image156 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image156);
  gtk_box_pack_start (GTK_BOX (hbox104), image156, FALSE, FALSE, 0);

  label316 = gtk_label_new_with_mnemonic (_("    Confirmer   "));
  gtk_widget_show (label316);
  gtk_box_pack_start (GTK_BOX (hbox104), label316, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label316, 100, 24);

  chayma_checkbutton_aj = gtk_check_button_new_with_mnemonic (_(" I'm not Robot"));
  gtk_widget_show (chayma_checkbutton_aj);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_checkbutton_aj, 368, 544);
  gtk_widget_set_size_request (chayma_checkbutton_aj, 144, 24);

  g_signal_connect ((gpointer) chayma_spinbutton_aj_NumBV, "changed",
                    G_CALLBACK (on_chayma_spinbutton_aj_NumBV_changed),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_aj_ret, "clicked",
                    G_CALLBACK (on_chayma_button_aj_ret_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_aj_conf, "clicked",
                    G_CALLBACK (on_chayma_button_aj_conf_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_checkbutton_aj, "activate",
                    G_CALLBACK (on_chayma_checkbutton_aj_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_reclamation, ajouter_reclamation, "ajouter_reclamation");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, fixed51, "fixed51");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_entry_aj_id, "chayma_entry_aj_id");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_entry_aj_listelec, "chayma_entry_aj_listelec");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_entry_aj_obj, "chayma_entry_aj_obj");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label308, "label308");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label310, "label310");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label311, "label311");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label312, "label312");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label313, "label313");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label314, "label314");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label315, "label315");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_textview_aj_msg, "chayma_textview_aj_msg");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_spinbutton_aj_NumBV, "chayma_spinbutton_aj_NumBV");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label309, "label309");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_combobox_aj_type, "chayma_combobox_aj_type");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, image155, "image155");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, image157, "image157");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_button_aj_ret, "chayma_button_aj_ret");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, alignment105, "alignment105");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, hbox105, "hbox105");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, image158, "image158");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label317, "label317");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_button_aj_conf, "chayma_button_aj_conf");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, alignment104, "alignment104");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, hbox104, "hbox104");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, image156, "image156");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label316, "label316");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_checkbutton_aj, "chayma_checkbutton_aj");

  return ajouter_reclamation;
}

