/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_modifier_reclamation (void);
GtkWidget* create_Liste_reclamation (void);
GtkWidget* create_Log_in (void);
GtkWidget* create_ajouter_reclamation (void);
GtkWidget* create_chayma_window_suprec (void);
