/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_modifier_reclamation (void)
{
  GtkWidget *modifier_reclamation;
  GtkWidget *fixed42;
  GtkWidget *chayma_entry_mdf_id;
  GtkWidget *chayma_entry_mdf_listele;
  GtkWidget *label252;
  GtkWidget *label255;
  GtkWidget *label256;
  GtkWidget *label257;
  GtkWidget *label259;
  GtkObject *chayma_spinbutton_mdf_NumBV_adj;
  GtkWidget *chayma_spinbutton_mdf_NumBV;
  GtkWidget *image115;
  GtkWidget *label258;
  GtkWidget *chayma_combobox_mdf_etat;
  GtkWidget *chayma_button_mdf_conf;
  GtkWidget *alignment80;
  GtkWidget *hbox80;
  GtkWidget *image112;
  GtkWidget *label261;
  GtkWidget *label254;
  GtkWidget *chayma_checkbutton_mdf;
  GtkWidget *chayma_entry_mdf_msg;
  GtkWidget *chayma_combobox_mdf_typ;
  GtkWidget *label253;
  GtkWidget *image114;
  GtkWidget *chayma_button_mdf_re;
  GtkWidget *alignment79;
  GtkWidget *hbox79;
  GtkWidget *image111;
  GtkWidget *label260;

  modifier_reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (modifier_reclamation), _("Modifier reclamation"));

  fixed42 = gtk_fixed_new ();
  gtk_widget_show (fixed42);
  gtk_container_add (GTK_CONTAINER (modifier_reclamation), fixed42);

  chayma_entry_mdf_id = gtk_entry_new ();
  gtk_widget_show (chayma_entry_mdf_id);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_entry_mdf_id, 368, 136);
  gtk_widget_set_size_request (chayma_entry_mdf_id, 176, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (chayma_entry_mdf_id), 8226);

  chayma_entry_mdf_listele = gtk_entry_new ();
  gtk_widget_show (chayma_entry_mdf_listele);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_entry_mdf_listele, 368, 232);
  gtk_widget_set_size_request (chayma_entry_mdf_listele, 176, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (chayma_entry_mdf_listele), 8226);

  label252 = gtk_label_new ("");
  gtk_widget_show (label252);
  gtk_fixed_put (GTK_FIXED (fixed42), label252, 208, 432);
  gtk_widget_set_size_request (label252, 49, 17);

  label255 = gtk_label_new (_("NUMERO DU BUREAU DE VOTE :"));
  gtk_widget_show (label255);
  gtk_fixed_put (GTK_FIXED (fixed42), label255, 64, 176);
  gtk_widget_set_size_request (label255, 256, 41);

  label256 = gtk_label_new (_("LISTE ELECTORALE :"));
  gtk_widget_show (label256);
  gtk_fixed_put (GTK_FIXED (fixed42), label256, 88, 232);
  gtk_widget_set_size_request (label256, 224, 33);

  label257 = gtk_label_new (_("TYPE DE RECLAMATION :"));
  gtk_widget_show (label257);
  gtk_fixed_put (GTK_FIXED (fixed42), label257, 112, 288);
  gtk_widget_set_size_request (label257, 192, 40);

  label259 = gtk_label_new (_("MESSAGE :"));
  gtk_widget_show (label259);
  gtk_fixed_put (GTK_FIXED (fixed42), label259, 152, 400);
  gtk_widget_set_size_request (label259, 112, 24);

  chayma_spinbutton_mdf_NumBV_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  chayma_spinbutton_mdf_NumBV = gtk_spin_button_new (GTK_ADJUSTMENT (chayma_spinbutton_mdf_NumBV_adj), 1, 0);
  gtk_widget_show (chayma_spinbutton_mdf_NumBV);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_spinbutton_mdf_NumBV, 368, 184);
  gtk_widget_set_size_request (chayma_spinbutton_mdf_NumBV, 60, 27);

  image115 = create_pixmap (modifier_reclamation, "images.png");
  gtk_widget_show (image115);
  gtk_fixed_put (GTK_FIXED (fixed42), image115, 584, 80);
  gtk_widget_set_size_request (image115, 232, 256);

  label258 = gtk_label_new (_("ETAT DE RECLAMATION:"));
  gtk_widget_show (label258);
  gtk_fixed_put (GTK_FIXED (fixed42), label258, 120, 328);
  gtk_widget_set_size_request (label258, 168, 40);

  chayma_combobox_mdf_etat = gtk_combo_box_new_text ();
  gtk_widget_show (chayma_combobox_mdf_etat);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_combobox_mdf_etat, 368, 336);
  gtk_widget_set_size_request (chayma_combobox_mdf_etat, 182, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (chayma_combobox_mdf_etat), _("Urgent"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (chayma_combobox_mdf_etat), _("Normal"));

  chayma_button_mdf_conf = gtk_button_new ();
  gtk_widget_show (chayma_button_mdf_conf);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_button_mdf_conf, 624, 544);
  gtk_widget_set_size_request (chayma_button_mdf_conf, 176, 48);

  alignment80 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment80);
  gtk_container_add (GTK_CONTAINER (chayma_button_mdf_conf), alignment80);

  hbox80 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox80);
  gtk_container_add (GTK_CONTAINER (alignment80), hbox80);

  image112 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image112);
  gtk_box_pack_start (GTK_BOX (hbox80), image112, FALSE, FALSE, 0);

  label261 = gtk_label_new_with_mnemonic (_("<b><span color=\"green\"> Confirmer</span></b>"));
  gtk_widget_show (label261);
  gtk_box_pack_start (GTK_BOX (hbox80), label261, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label261), TRUE);

  label254 = gtk_label_new_with_mnemonic (_("Identifiant"));
  gtk_widget_show (label254);
  gtk_fixed_put (GTK_FIXED (fixed42), label254, 160, 136);
  gtk_widget_set_size_request (label254, 88, 33);
  gtk_label_set_use_markup (GTK_LABEL (label254), TRUE);

  chayma_checkbutton_mdf = gtk_check_button_new_with_mnemonic (_(" I'm not Robot"));
  gtk_widget_show (chayma_checkbutton_mdf);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_checkbutton_mdf, 368, 544);
  gtk_widget_set_size_request (chayma_checkbutton_mdf, 144, 24);

  chayma_entry_mdf_msg = gtk_entry_new ();
  gtk_widget_show (chayma_entry_mdf_msg);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_entry_mdf_msg, 368, 392);
  gtk_widget_set_size_request (chayma_entry_mdf_msg, 176, 104);
  gtk_entry_set_invisible_char (GTK_ENTRY (chayma_entry_mdf_msg), 8226);

  chayma_combobox_mdf_typ = gtk_combo_box_new_text ();
  gtk_widget_show (chayma_combobox_mdf_typ);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_combobox_mdf_typ, 368, 288);
  gtk_widget_set_size_request (chayma_combobox_mdf_typ, 182, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (chayma_combobox_mdf_typ), _("pratique "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (chayma_combobox_mdf_typ), _("theorique"));

  label253 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\"> Modifer Reclamation</span></b>"));
  gtk_widget_show (label253);
  gtk_fixed_put (GTK_FIXED (fixed42), label253, 312, 24);
  gtk_widget_set_size_request (label253, 208, 48);
  gtk_label_set_use_markup (GTK_LABEL (label253), TRUE);

  image114 = create_pixmap (modifier_reclamation, "index.png");
  gtk_widget_show (image114);
  gtk_fixed_put (GTK_FIXED (fixed42), image114, 0, 0);
  gtk_widget_set_size_request (image114, 184, 136);

  chayma_button_mdf_re = gtk_button_new ();
  gtk_widget_show (chayma_button_mdf_re);
  gtk_fixed_put (GTK_FIXED (fixed42), chayma_button_mdf_re, 56, 552);
  gtk_widget_set_size_request (chayma_button_mdf_re, 160, 48);

  alignment79 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment79);
  gtk_container_add (GTK_CONTAINER (chayma_button_mdf_re), alignment79);

  hbox79 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox79);
  gtk_container_add (GTK_CONTAINER (alignment79), hbox79);

  image111 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image111);
  gtk_box_pack_start (GTK_BOX (hbox79), image111, FALSE, FALSE, 0);

  label260 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Retour</span></b>"));
  gtk_widget_show (label260);
  gtk_box_pack_start (GTK_BOX (hbox79), label260, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label260), TRUE);

  g_signal_connect ((gpointer) modifier_reclamation, "focus_in_event",
                    G_CALLBACK (on_modier_reclamation_focus_in_event),
                    NULL);
  g_signal_connect ((gpointer) chayma_entry_mdf_id, "insert_text",
                    G_CALLBACK (on_chayma_entry_mdf_id_insert_text),
                    NULL);
  g_signal_connect ((gpointer) chayma_entry_mdf_listele, "insert_text",
                    G_CALLBACK (on_chayma_entry_mdf_listele_insert_text),
                    NULL);
  g_signal_connect ((gpointer) chayma_spinbutton_mdf_NumBV, "changed",
                    G_CALLBACK (on_chayma_spinbutton_mdf_NumBV_changed),
                    NULL);
  g_signal_connect ((gpointer) chayma_combobox_mdf_etat, "changed",
                    G_CALLBACK (on_chayma_combobox_mdf_etat_changed),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_mdf_conf, "clicked",
                    G_CALLBACK (on_chayma_button_mdf_conf_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_checkbutton_mdf, "toggled",
                    G_CALLBACK (on_chayma_checkbutton_mdf_toggled),
                    NULL);
  g_signal_connect ((gpointer) chayma_entry_mdf_msg, "insert_text",
                    G_CALLBACK (on_chayma_entry_mdf_msg_insert_text),
                    NULL);
  g_signal_connect ((gpointer) chayma_combobox_mdf_typ, "changed",
                    G_CALLBACK (on_chayma_combobox_mdf_typ_changed),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_mdf_re, "clicked",
                    G_CALLBACK (on_chayma_button_mdf_re_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label254), chayma_entry_mdf_id);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_reclamation, modifier_reclamation, "modifier_reclamation");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, fixed42, "fixed42");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, chayma_entry_mdf_id, "chayma_entry_mdf_id");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, chayma_entry_mdf_listele, "chayma_entry_mdf_listele");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, label252, "label252");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, label255, "label255");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, label256, "label256");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, label257, "label257");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, label259, "label259");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, chayma_spinbutton_mdf_NumBV, "chayma_spinbutton_mdf_NumBV");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, image115, "image115");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, label258, "label258");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, chayma_combobox_mdf_etat, "chayma_combobox_mdf_etat");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, chayma_button_mdf_conf, "chayma_button_mdf_conf");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, alignment80, "alignment80");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, hbox80, "hbox80");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, image112, "image112");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, label261, "label261");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, label254, "label254");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, chayma_checkbutton_mdf, "chayma_checkbutton_mdf");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, chayma_entry_mdf_msg, "chayma_entry_mdf_msg");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, chayma_combobox_mdf_typ, "chayma_combobox_mdf_typ");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, label253, "label253");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, image114, "image114");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, chayma_button_mdf_re, "chayma_button_mdf_re");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, alignment79, "alignment79");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, hbox79, "hbox79");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, image111, "image111");
  GLADE_HOOKUP_OBJECT (modifier_reclamation, label260, "label260");

  return modifier_reclamation;
}

GtkWidget*
create_Liste_reclamation (void)
{
  GtkWidget *Liste_reclamation;
  GtkWidget *fixed48;
  GtkWidget *chayma_treeview_ls;
  GtkWidget *chayma_entry_ls_numlist;
  GtkWidget *label302;
  GtkWidget *image146;
  GtkWidget *chayma_button_ls_recherche;
  GtkWidget *alignment102;
  GtkWidget *hbox102;
  GtkWidget *image147;
  GtkWidget *label301;
  GtkWidget *chayma_button_ls_actualiser;
  GtkWidget *alignment106;
  GtkWidget *hbox106;
  GtkWidget *image159;
  GtkWidget *label318;
  GtkWidget *chayma_button_ls_dec;
  GtkWidget *alignment96;
  GtkWidget *hbox96;
  GtkWidget *image140;
  GtkWidget *label293;
  GtkWidget *chayma_button_ls_ajout;
  GtkWidget *alignment97;
  GtkWidget *hbox97;
  GtkWidget *image141;
  GtkWidget *label294;
  GtkWidget *chayma_button_ls_mdf;
  GtkWidget *alignment98;
  GtkWidget *hbox98;
  GtkWidget *image142;
  GtkWidget *label295;
  GtkWidget *chayma_button_ls_sup;
  GtkWidget *alignment99;
  GtkWidget *hbox99;
  GtkWidget *image143;
  GtkWidget *label296;
  GtkWidget *chayma_radiobutton_ls_type;
  GSList *chayma_radiobutton_ls_type_group = NULL;
  GtkWidget *chayma_radiobutton_ls_Etat;
  GtkWidget *label300;
  GtkWidget *label297;
  GtkWidget *chayma_button_stat_gag;
  GtkWidget *alignment100;
  GtkWidget *hbox100;
  GtkWidget *image144;
  GtkWidget *label319;
  GtkWidget *chayma_button_stat_rec;
  GtkWidget *alignment101;
  GtkWidget *hbox101;
  GtkWidget *image145;
  GtkWidget *label320;

  Liste_reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Liste_reclamation), _("Liste reclamation"));

  fixed48 = gtk_fixed_new ();
  gtk_widget_show (fixed48);
  gtk_container_add (GTK_CONTAINER (Liste_reclamation), fixed48);
  gtk_widget_set_size_request (fixed48, 904, 640);

  chayma_treeview_ls = gtk_tree_view_new ();
  gtk_widget_show (chayma_treeview_ls);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_treeview_ls, 32, 168);
  gtk_widget_set_size_request (chayma_treeview_ls, 480, 288);

  chayma_entry_ls_numlist = gtk_entry_new ();
  gtk_widget_show (chayma_entry_ls_numlist);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_entry_ls_numlist, 688, 168);
  gtk_widget_set_size_request (chayma_entry_ls_numlist, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (chayma_entry_ls_numlist), 8226);

  label302 = gtk_label_new (_("Num liste electorale"));
  gtk_widget_show (label302);
  gtk_fixed_put (GTK_FIXED (fixed48), label302, 688, 120);
  gtk_widget_set_size_request (label302, 161, 24);

  image146 = create_pixmap (Liste_reclamation, "index.png");
  gtk_widget_show (image146);
  gtk_fixed_put (GTK_FIXED (fixed48), image146, 0, 0);
  gtk_widget_set_size_request (image146, 184, 136);

  chayma_button_ls_recherche = gtk_button_new ();
  gtk_widget_show (chayma_button_ls_recherche);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_ls_recherche, 552, 168);
  gtk_widget_set_size_request (chayma_button_ls_recherche, 120, 32);

  alignment102 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment102);
  gtk_container_add (GTK_CONTAINER (chayma_button_ls_recherche), alignment102);

  hbox102 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox102);
  gtk_container_add (GTK_CONTAINER (alignment102), hbox102);

  image147 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image147);
  gtk_box_pack_start (GTK_BOX (hbox102), image147, FALSE, FALSE, 0);

  label301 = gtk_label_new_with_mnemonic (_(" <b><span color=\"black\">Recherche</span></b>"));
  gtk_widget_show (label301);
  gtk_box_pack_start (GTK_BOX (hbox102), label301, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label301), TRUE);

  chayma_button_ls_actualiser = gtk_button_new ();
  gtk_widget_show (chayma_button_ls_actualiser);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_ls_actualiser, 224, 88);
  gtk_widget_set_size_request (chayma_button_ls_actualiser, 112, 40);

  alignment106 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment106);
  gtk_container_add (GTK_CONTAINER (chayma_button_ls_actualiser), alignment106);

  hbox106 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox106);
  gtk_container_add (GTK_CONTAINER (alignment106), hbox106);

  image159 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image159);
  gtk_box_pack_start (GTK_BOX (hbox106), image159, FALSE, FALSE, 0);

  label318 = gtk_label_new_with_mnemonic (_(" <b><span color=\"black\">Actualiser</span></b>"));
  gtk_widget_show (label318);
  gtk_box_pack_start (GTK_BOX (hbox106), label318, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label318), TRUE);

  chayma_button_ls_dec = gtk_button_new ();
  gtk_widget_show (chayma_button_ls_dec);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_ls_dec, 40, 576);
  gtk_widget_set_size_request (chayma_button_ls_dec, 144, 40);

  alignment96 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment96);
  gtk_container_add (GTK_CONTAINER (chayma_button_ls_dec), alignment96);

  hbox96 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox96);
  gtk_container_add (GTK_CONTAINER (alignment96), hbox96);

  image140 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image140);
  gtk_box_pack_start (GTK_BOX (hbox96), image140, FALSE, FALSE, 0);

  label293 = gtk_label_new_with_mnemonic (_(" <b><span color=\"black\">Deconnecter</span></b>"));
  gtk_widget_show (label293);
  gtk_box_pack_start (GTK_BOX (hbox96), label293, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label293), TRUE);

  chayma_button_ls_ajout = gtk_button_new ();
  gtk_widget_show (chayma_button_ls_ajout);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_ls_ajout, 104, 504);
  gtk_widget_set_size_request (chayma_button_ls_ajout, 168, 48);

  alignment97 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment97);
  gtk_container_add (GTK_CONTAINER (chayma_button_ls_ajout), alignment97);

  hbox97 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox97);
  gtk_container_add (GTK_CONTAINER (alignment97), hbox97);

  image141 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image141);
  gtk_box_pack_start (GTK_BOX (hbox97), image141, FALSE, FALSE, 0);

  label294 = gtk_label_new_with_mnemonic (_("<b><span color=\"blue\"> Ajouter </span></b>"));
  gtk_widget_show (label294);
  gtk_box_pack_start (GTK_BOX (hbox97), label294, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label294), TRUE);

  chayma_button_ls_mdf = gtk_button_new ();
  gtk_widget_show (chayma_button_ls_mdf);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_ls_mdf, 288, 504);
  gtk_widget_set_size_request (chayma_button_ls_mdf, 168, 48);

  alignment98 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment98);
  gtk_container_add (GTK_CONTAINER (chayma_button_ls_mdf), alignment98);

  hbox98 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox98);
  gtk_container_add (GTK_CONTAINER (alignment98), hbox98);

  image142 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image142);
  gtk_box_pack_start (GTK_BOX (hbox98), image142, FALSE, FALSE, 0);

  label295 = gtk_label_new_with_mnemonic (_("<b><span color=\"blue\"> Mdifier</span></b>"));
  gtk_widget_show (label295);
  gtk_box_pack_start (GTK_BOX (hbox98), label295, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label295), TRUE);

  chayma_button_ls_sup = gtk_button_new ();
  gtk_widget_show (chayma_button_ls_sup);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_ls_sup, 464, 504);
  gtk_widget_set_size_request (chayma_button_ls_sup, 168, 48);

  alignment99 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment99);
  gtk_container_add (GTK_CONTAINER (chayma_button_ls_sup), alignment99);

  hbox99 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox99);
  gtk_container_add (GTK_CONTAINER (alignment99), hbox99);

  image143 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image143);
  gtk_box_pack_start (GTK_BOX (hbox99), image143, FALSE, FALSE, 0);

  label296 = gtk_label_new_with_mnemonic (_("<b><span color=\"blue\"> Supprimer</span></b>"));
  gtk_widget_show (label296);
  gtk_box_pack_start (GTK_BOX (hbox99), label296, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label296), TRUE);

  chayma_radiobutton_ls_type = gtk_radio_button_new_with_mnemonic (NULL, _("type"));
  gtk_widget_show (chayma_radiobutton_ls_type);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_radiobutton_ls_type, 560, 280);
  gtk_widget_set_size_request (chayma_radiobutton_ls_type, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (chayma_radiobutton_ls_type), chayma_radiobutton_ls_type_group);
  chayma_radiobutton_ls_type_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (chayma_radiobutton_ls_type));

  chayma_radiobutton_ls_Etat = gtk_radio_button_new_with_mnemonic (NULL, _("Etat"));
  gtk_widget_show (chayma_radiobutton_ls_Etat);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_radiobutton_ls_Etat, 560, 232);
  gtk_widget_set_size_request (chayma_radiobutton_ls_Etat, 120, 32);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (chayma_radiobutton_ls_Etat), chayma_radiobutton_ls_type_group);
  chayma_radiobutton_ls_type_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (chayma_radiobutton_ls_Etat));

  label300 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\">LISTE RECLAMATION</span></b>"));
  gtk_widget_show (label300);
  gtk_fixed_put (GTK_FIXED (fixed48), label300, 368, 8);
  gtk_widget_set_size_request (label300, 216, 33);
  gtk_label_set_use_markup (GTK_LABEL (label300), TRUE);

  label297 = gtk_label_new ("");
  gtk_widget_show (label297);
  gtk_fixed_put (GTK_FIXED (fixed48), label297, 272, 576);
  gtk_widget_set_size_request (label297, 376, 64);

  chayma_button_stat_gag = gtk_button_new ();
  gtk_widget_show (chayma_button_stat_gag);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_stat_gag, 752, 504);
  gtk_widget_set_size_request (chayma_button_stat_gag, 152, 48);

  alignment100 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment100);
  gtk_container_add (GTK_CONTAINER (chayma_button_stat_gag), alignment100);

  hbox100 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox100);
  gtk_container_add (GTK_CONTAINER (alignment100), hbox100);

  image144 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image144);
  gtk_box_pack_start (GTK_BOX (hbox100), image144, FALSE, FALSE, 0);

  label319 = gtk_label_new_with_mnemonic (_("<b><span color=\"green\"> Les conseillers \n     gagnants</span></b>"));
  gtk_widget_show (label319);
  gtk_box_pack_start (GTK_BOX (hbox100), label319, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label319), TRUE);

  chayma_button_stat_rec = gtk_button_new ();
  gtk_widget_show (chayma_button_stat_rec);
  gtk_fixed_put (GTK_FIXED (fixed48), chayma_button_stat_rec, 752, 568);
  gtk_widget_set_size_request (chayma_button_stat_rec, 152, 72);

  alignment101 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment101);
  gtk_container_add (GTK_CONTAINER (chayma_button_stat_rec), alignment101);

  hbox101 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox101);
  gtk_container_add (GTK_CONTAINER (alignment101), hbox101);

  image145 = gtk_image_new_from_stock ("gtk-about", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image145);
  gtk_box_pack_start (GTK_BOX (hbox101), image145, FALSE, FALSE, 0);

  label320 = gtk_label_new_with_mnemonic (_(" <b><span color=\"green\">     Nombre \nde reclamation \n     par liste \n     </span></b>"));
  gtk_widget_show (label320);
  gtk_box_pack_start (GTK_BOX (hbox101), label320, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label320), TRUE);

  g_signal_connect ((gpointer) Liste_reclamation, "focus_in_event",
                    G_CALLBACK (on_Liste_reclamation_focus_in_event),
                    NULL);
  g_signal_connect ((gpointer) chayma_treeview_ls, "row_activated",
                    G_CALLBACK (on_chayma_treeview_row_activated),
                    NULL);
  g_signal_connect ((gpointer) chayma_entry_ls_numlist, "insert_text",
                    G_CALLBACK (on_chayma_entry_ls_numlist_insert_text),
                    NULL);
  g_signal_connect ((gpointer) chayma_entry_ls_numlist, "changed",
                    G_CALLBACK (on_chayma_entry_ls_numlist_changed),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_ls_recherche, "clicked",
                    G_CALLBACK (on_chayma_button_ls_recherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_ls_actualiser, "clicked",
                    G_CALLBACK (on_chayma_button_ls_actualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_ls_dec, "clicked",
                    G_CALLBACK (on_chayma_button_ls_dec_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_ls_ajout, "clicked",
                    G_CALLBACK (on_chayma_button_ls_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_ls_mdf, "clicked",
                    G_CALLBACK (on_chayma_button_ls_mdf_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_ls_sup, "clicked",
                    G_CALLBACK (on_chayma_button_ls_sup_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_radiobutton_ls_type, "toggled",
                    G_CALLBACK (on_chayma_radiobutton_ls_type_toggled),
                    NULL);
  g_signal_connect ((gpointer) chayma_radiobutton_ls_Etat, "toggled",
                    G_CALLBACK (on_chayma_radiobutton_ls_Etat_toggled),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_stat_gag, "clicked",
                    G_CALLBACK (on_chayma_button_stat_gag_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_stat_rec, "clicked",
                    G_CALLBACK (on_chayma_button_stat_rec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Liste_reclamation, Liste_reclamation, "Liste_reclamation");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, fixed48, "fixed48");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_treeview_ls, "chayma_treeview_ls");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_entry_ls_numlist, "chayma_entry_ls_numlist");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label302, "label302");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image146, "image146");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_ls_recherche, "chayma_button_ls_recherche");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment102, "alignment102");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox102, "hbox102");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image147, "image147");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label301, "label301");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_ls_actualiser, "chayma_button_ls_actualiser");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment106, "alignment106");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox106, "hbox106");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image159, "image159");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label318, "label318");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_ls_dec, "chayma_button_ls_dec");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment96, "alignment96");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox96, "hbox96");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image140, "image140");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label293, "label293");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_ls_ajout, "chayma_button_ls_ajout");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment97, "alignment97");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox97, "hbox97");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image141, "image141");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label294, "label294");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_ls_mdf, "chayma_button_ls_mdf");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment98, "alignment98");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox98, "hbox98");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image142, "image142");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label295, "label295");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_ls_sup, "chayma_button_ls_sup");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment99, "alignment99");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox99, "hbox99");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image143, "image143");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label296, "label296");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_radiobutton_ls_type, "chayma_radiobutton_ls_type");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_radiobutton_ls_Etat, "chayma_radiobutton_ls_Etat");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label300, "label300");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label297, "label297");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_stat_gag, "chayma_button_stat_gag");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment100, "alignment100");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox100, "hbox100");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image144, "image144");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label319, "label319");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, chayma_button_stat_rec, "chayma_button_stat_rec");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, alignment101, "alignment101");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, hbox101, "hbox101");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, image145, "image145");
  GLADE_HOOKUP_OBJECT (Liste_reclamation, label320, "label320");

  return Liste_reclamation;
}

GtkWidget*
create_Log_in (void)
{
  GtkWidget *Log_in;
  GtkWidget *fixed50;
  GtkWidget *ident_log_in;
  GtkWidget *mdp_log_in;
  GtkWidget *image154;
  GtkWidget *connecter;
  GtkWidget *alignment103;
  GtkWidget *hbox103;
  GtkWidget *image153;
  GtkWidget *label306;
  GtkWidget *label304;
  GtkWidget *label305;
  GtkWidget *label_log_in;
  GtkWidget *label303;

  Log_in = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Log_in, 480, 420);
  gtk_window_set_title (GTK_WINDOW (Log_in), _("Log in"));

  fixed50 = gtk_fixed_new ();
  gtk_widget_show (fixed50);
  gtk_container_add (GTK_CONTAINER (Log_in), fixed50);
  gtk_widget_set_size_request (fixed50, 480, 416);

  ident_log_in = gtk_entry_new ();
  gtk_widget_show (ident_log_in);
  gtk_fixed_put (GTK_FIXED (fixed50), ident_log_in, 216, 168);
  gtk_widget_set_size_request (ident_log_in, 250, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (ident_log_in), 8226);

  mdp_log_in = gtk_entry_new ();
  gtk_widget_show (mdp_log_in);
  gtk_fixed_put (GTK_FIXED (fixed50), mdp_log_in, 216, 232);
  gtk_widget_set_size_request (mdp_log_in, 250, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (mdp_log_in), 8226);

  image154 = create_pixmap (Log_in, "index.png");
  gtk_widget_show (image154);
  gtk_fixed_put (GTK_FIXED (fixed50), image154, 0, 0);
  gtk_widget_set_size_request (image154, 176, 128);

  connecter = gtk_button_new ();
  gtk_widget_show (connecter);
  gtk_fixed_put (GTK_FIXED (fixed50), connecter, 264, 296);
  gtk_widget_set_size_request (connecter, 143, 38);

  alignment103 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment103);
  gtk_container_add (GTK_CONTAINER (connecter), alignment103);

  hbox103 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox103);
  gtk_container_add (GTK_CONTAINER (alignment103), hbox103);

  image153 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image153);
  gtk_box_pack_start (GTK_BOX (hbox103), image153, FALSE, FALSE, 0);

  label306 = gtk_label_new_with_mnemonic (_("<b><span color=\"green\"> CONNECTER</span></b>"));
  gtk_widget_show (label306);
  gtk_box_pack_start (GTK_BOX (hbox103), label306, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label306), TRUE);

  label304 = gtk_label_new_with_mnemonic (_("<b><span color=\"blue\"> identifiant</span></b>"));
  gtk_widget_show (label304);
  gtk_fixed_put (GTK_FIXED (fixed50), label304, 40, 168);
  gtk_widget_set_size_request (label304, 176, 40);
  gtk_label_set_use_markup (GTK_LABEL (label304), TRUE);

  label305 = gtk_label_new_with_mnemonic (_("<b><span color=\"blue\"> Mot de passe</span></b>"));
  gtk_widget_show (label305);
  gtk_fixed_put (GTK_FIXED (fixed50), label305, 48, 232);
  gtk_widget_set_size_request (label305, 160, 32);
  gtk_label_set_use_markup (GTK_LABEL (label305), TRUE);

  label_log_in = gtk_label_new ("");
  gtk_widget_show (label_log_in);
  gtk_fixed_put (GTK_FIXED (fixed50), label_log_in, 120, 376);
  gtk_widget_set_size_request (label_log_in, 312, 40);

  label303 = gtk_label_new_with_mnemonic (_("<b><span color=\"RED\"> CONNECTER</span></b>"));
  gtk_widget_show (label303);
  gtk_fixed_put (GTK_FIXED (fixed50), label303, 176, 88);
  gtk_widget_set_size_request (label303, 304, 40);
  gtk_label_set_use_markup (GTK_LABEL (label303), TRUE);

  g_signal_connect ((gpointer) ident_log_in, "insert_text",
                    G_CALLBACK (on_ident_log_in_insert_text),
                    NULL);
  g_signal_connect ((gpointer) mdp_log_in, "insert_text",
                    G_CALLBACK (on_mdp_log_in_insert_text),
                    NULL);
  g_signal_connect ((gpointer) connecter, "clicked",
                    G_CALLBACK (on_connecter_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label304), ident_log_in);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label305), mdp_log_in);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Log_in, Log_in, "Log_in");
  GLADE_HOOKUP_OBJECT (Log_in, fixed50, "fixed50");
  GLADE_HOOKUP_OBJECT (Log_in, ident_log_in, "ident_log_in");
  GLADE_HOOKUP_OBJECT (Log_in, mdp_log_in, "mdp_log_in");
  GLADE_HOOKUP_OBJECT (Log_in, image154, "image154");
  GLADE_HOOKUP_OBJECT (Log_in, connecter, "connecter");
  GLADE_HOOKUP_OBJECT (Log_in, alignment103, "alignment103");
  GLADE_HOOKUP_OBJECT (Log_in, hbox103, "hbox103");
  GLADE_HOOKUP_OBJECT (Log_in, image153, "image153");
  GLADE_HOOKUP_OBJECT (Log_in, label306, "label306");
  GLADE_HOOKUP_OBJECT (Log_in, label304, "label304");
  GLADE_HOOKUP_OBJECT (Log_in, label305, "label305");
  GLADE_HOOKUP_OBJECT (Log_in, label_log_in, "label_log_in");
  GLADE_HOOKUP_OBJECT (Log_in, label303, "label303");

  return Log_in;
}

GtkWidget*
create_ajouter_reclamation (void)
{
  GtkWidget *ajouter_reclamation;
  GtkWidget *fixed51;
  GtkWidget *chayma_entry_aj_id;
  GtkWidget *chayma_entry_aj_listelec;
  GtkWidget *label308;
  GtkWidget *label310;
  GtkWidget *label312;
  GtkWidget *label314;
  GtkObject *chayma_spinbutton_aj_NumBV_adj;
  GtkWidget *chayma_spinbutton_aj_NumBV;
  GtkWidget *label309;
  GtkWidget *image155;
  GtkWidget *image157;
  GtkWidget *label311;
  GtkWidget *label313;
  GtkWidget *chayma_combobox_aj_etat;
  GtkWidget *chayma_button_aj_ret;
  GtkWidget *alignment105;
  GtkWidget *hbox105;
  GtkWidget *image158;
  GtkWidget *label317;
  GtkWidget *chayma_button_aj_conf;
  GtkWidget *alignment104;
  GtkWidget *hbox104;
  GtkWidget *image156;
  GtkWidget *label316;
  GtkWidget *chayma_checkbutton_aj;
  GtkWidget *chayma_combobox_aj_type;
  GtkWidget *chayma_entry_aj_msg;
  GtkWidget *label315;

  ajouter_reclamation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ajouter_reclamation), _("Ajouter reclamation"));

  fixed51 = gtk_fixed_new ();
  gtk_widget_show (fixed51);
  gtk_container_add (GTK_CONTAINER (ajouter_reclamation), fixed51);

  chayma_entry_aj_id = gtk_entry_new ();
  gtk_widget_show (chayma_entry_aj_id);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_entry_aj_id, 352, 136);
  gtk_widget_set_size_request (chayma_entry_aj_id, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (chayma_entry_aj_id), 8226);

  chayma_entry_aj_listelec = gtk_entry_new ();
  gtk_widget_show (chayma_entry_aj_listelec);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_entry_aj_listelec, 352, 240);
  gtk_widget_set_size_request (chayma_entry_aj_listelec, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (chayma_entry_aj_listelec), 8226);

  label308 = gtk_label_new ("");
  gtk_widget_show (label308);
  gtk_fixed_put (GTK_FIXED (fixed51), label308, 208, 432);
  gtk_widget_set_size_request (label308, 49, 17);

  label310 = gtk_label_new (_("NUMERO DU BUREAU DE VOTE :"));
  gtk_widget_show (label310);
  gtk_fixed_put (GTK_FIXED (fixed51), label310, 64, 176);
  gtk_widget_set_size_request (label310, 256, 41);

  label312 = gtk_label_new (_("TYPE DE RECLAMATION :"));
  gtk_widget_show (label312);
  gtk_fixed_put (GTK_FIXED (fixed51), label312, 112, 288);
  gtk_widget_set_size_request (label312, 192, 40);

  label314 = gtk_label_new (_("MESSAGE :"));
  gtk_widget_show (label314);
  gtk_fixed_put (GTK_FIXED (fixed51), label314, 152, 400);
  gtk_widget_set_size_request (label314, 112, 24);

  chayma_spinbutton_aj_NumBV_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  chayma_spinbutton_aj_NumBV = gtk_spin_button_new (GTK_ADJUSTMENT (chayma_spinbutton_aj_NumBV_adj), 1, 0);
  gtk_widget_show (chayma_spinbutton_aj_NumBV);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_spinbutton_aj_NumBV, 352, 184);
  gtk_widget_set_size_request (chayma_spinbutton_aj_NumBV, 60, 27);

  label309 = gtk_label_new (_("VOTRE ID :"));
  gtk_widget_show (label309);
  gtk_fixed_put (GTK_FIXED (fixed51), label309, 144, 128);
  gtk_widget_set_size_request (label309, 88, 33);

  image155 = create_pixmap (ajouter_reclamation, "images.png");
  gtk_widget_show (image155);
  gtk_fixed_put (GTK_FIXED (fixed51), image155, 608, 88);
  gtk_widget_set_size_request (image155, 232, 256);

  image157 = create_pixmap (ajouter_reclamation, "index.png");
  gtk_widget_show (image157);
  gtk_fixed_put (GTK_FIXED (fixed51), image157, 0, 0);
  gtk_widget_set_size_request (image157, 184, 136);

  label311 = gtk_label_new (_("NUM LISTE ELECTORALE :"));
  gtk_widget_show (label311);
  gtk_fixed_put (GTK_FIXED (fixed51), label311, 88, 232);
  gtk_widget_set_size_request (label311, 224, 33);

  label313 = gtk_label_new (_("ETAT DE RECLAMATION :"));
  gtk_widget_show (label313);
  gtk_fixed_put (GTK_FIXED (fixed51), label313, 112, 344);
  gtk_widget_set_size_request (label313, 184, 32);

  chayma_combobox_aj_etat = gtk_combo_box_new_text ();
  gtk_widget_show (chayma_combobox_aj_etat);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_combobox_aj_etat, 352, 344);
  gtk_widget_set_size_request (chayma_combobox_aj_etat, 182, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (chayma_combobox_aj_etat), _("Urgent"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (chayma_combobox_aj_etat), _("Normal"));

  chayma_button_aj_ret = gtk_button_new ();
  gtk_widget_show (chayma_button_aj_ret);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_button_aj_ret, 32, 552);
  gtk_widget_set_size_request (chayma_button_aj_ret, 168, 48);

  alignment105 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment105);
  gtk_container_add (GTK_CONTAINER (chayma_button_aj_ret), alignment105);

  hbox105 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox105);
  gtk_container_add (GTK_CONTAINER (alignment105), hbox105);

  image158 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image158);
  gtk_box_pack_start (GTK_BOX (hbox105), image158, FALSE, FALSE, 0);

  label317 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Retour</span></b>"));
  gtk_widget_show (label317);
  gtk_box_pack_start (GTK_BOX (hbox105), label317, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label317), TRUE);

  chayma_button_aj_conf = gtk_button_new ();
  gtk_widget_show (chayma_button_aj_conf);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_button_aj_conf, 704, 544);
  gtk_widget_set_size_request (chayma_button_aj_conf, 192, 56);

  alignment104 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment104);
  gtk_container_add (GTK_CONTAINER (chayma_button_aj_conf), alignment104);

  hbox104 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox104);
  gtk_container_add (GTK_CONTAINER (alignment104), hbox104);

  image156 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image156);
  gtk_box_pack_start (GTK_BOX (hbox104), image156, FALSE, FALSE, 0);

  label316 = gtk_label_new_with_mnemonic (_("<b><span color=\"green\"> Confirmer</span></b>"));
  gtk_widget_show (label316);
  gtk_box_pack_start (GTK_BOX (hbox104), label316, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label316, 100, 24);
  gtk_label_set_use_markup (GTK_LABEL (label316), TRUE);

  chayma_checkbutton_aj = gtk_check_button_new_with_mnemonic (_(" I'm not Robot"));
  gtk_widget_show (chayma_checkbutton_aj);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_checkbutton_aj, 368, 544);
  gtk_widget_set_size_request (chayma_checkbutton_aj, 144, 24);

  chayma_combobox_aj_type = gtk_combo_box_new_text ();
  gtk_widget_show (chayma_combobox_aj_type);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_combobox_aj_type, 352, 296);
  gtk_widget_set_size_request (chayma_combobox_aj_type, 182, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (chayma_combobox_aj_type), _("pratique "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (chayma_combobox_aj_type), _("theorique"));

  chayma_entry_aj_msg = gtk_entry_new ();
  gtk_widget_show (chayma_entry_aj_msg);
  gtk_fixed_put (GTK_FIXED (fixed51), chayma_entry_aj_msg, 352, 408);
  gtk_widget_set_size_request (chayma_entry_aj_msg, 160, 88);
  gtk_entry_set_invisible_char (GTK_ENTRY (chayma_entry_aj_msg), 8226);

  label315 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\"> Ajouter reclamation</span></b>"));
  gtk_widget_show (label315);
  gtk_fixed_put (GTK_FIXED (fixed51), label315, 344, 32);
  gtk_widget_set_size_request (label315, 208, 48);
  gtk_label_set_use_markup (GTK_LABEL (label315), TRUE);

  g_signal_connect ((gpointer) chayma_entry_aj_id, "insert_text",
                    G_CALLBACK (on_chayma_entry_aj_id_insert_text),
                    NULL);
  g_signal_connect ((gpointer) chayma_entry_aj_listelec, "insert_text",
                    G_CALLBACK (on_chayma_entry_aj_listelec_insert_text),
                    NULL);
  g_signal_connect ((gpointer) chayma_spinbutton_aj_NumBV, "changed",
                    G_CALLBACK (on_chayma_spinbutton_aj_NumBV_changed),
                    NULL);
  g_signal_connect ((gpointer) chayma_combobox_aj_etat, "changed",
                    G_CALLBACK (on_chayma_combobox_aj_etat_changed),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_aj_ret, "clicked",
                    G_CALLBACK (on_chayma_button_aj_ret_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_aj_conf, "clicked",
                    G_CALLBACK (on_chayma_button_aj_conf_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_checkbutton_aj, "toggled",
                    G_CALLBACK (on_chayma_checkbutton_aj_toggled),
                    NULL);
  g_signal_connect ((gpointer) chayma_combobox_aj_type, "changed",
                    G_CALLBACK (on_chayma_combobox_aj_type_changed),
                    NULL);
  g_signal_connect ((gpointer) chayma_entry_aj_msg, "insert_text",
                    G_CALLBACK (on_chayma_entry_aj_msg_insert_text),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajouter_reclamation, ajouter_reclamation, "ajouter_reclamation");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, fixed51, "fixed51");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_entry_aj_id, "chayma_entry_aj_id");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_entry_aj_listelec, "chayma_entry_aj_listelec");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label308, "label308");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label310, "label310");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label312, "label312");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label314, "label314");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_spinbutton_aj_NumBV, "chayma_spinbutton_aj_NumBV");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label309, "label309");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, image155, "image155");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, image157, "image157");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label311, "label311");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label313, "label313");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_combobox_aj_etat, "chayma_combobox_aj_etat");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_button_aj_ret, "chayma_button_aj_ret");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, alignment105, "alignment105");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, hbox105, "hbox105");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, image158, "image158");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label317, "label317");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_button_aj_conf, "chayma_button_aj_conf");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, alignment104, "alignment104");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, hbox104, "hbox104");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, image156, "image156");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label316, "label316");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_checkbutton_aj, "chayma_checkbutton_aj");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_combobox_aj_type, "chayma_combobox_aj_type");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, chayma_entry_aj_msg, "chayma_entry_aj_msg");
  GLADE_HOOKUP_OBJECT (ajouter_reclamation, label315, "label315");

  return ajouter_reclamation;
}

GtkWidget*
create_chayma_window_suprec (void)
{
  GtkWidget *chayma_window_suprec;
  GtkWidget *fixed52;
  GtkWidget *chayma_radiobutton_sup_rec;
  GSList *chayma_radiobutton_sup_rec_group = NULL;
  GtkWidget *chayma_radiobutton_sup_non;
  GtkWidget *label321;
  GtkWidget *chayma_button_conf_suprec;
  GtkWidget *alignment107;
  GtkWidget *hbox107;
  GtkWidget *image160;
  GtkWidget *label322;

  chayma_window_suprec = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (chayma_window_suprec, 461, 261);
  gtk_window_set_title (GTK_WINDOW (chayma_window_suprec), _("sup_rec"));

  fixed52 = gtk_fixed_new ();
  gtk_widget_show (fixed52);
  gtk_container_add (GTK_CONTAINER (chayma_window_suprec), fixed52);
  gtk_widget_set_size_request (fixed52, 464, 264);

  chayma_radiobutton_sup_rec = gtk_radio_button_new_with_mnemonic (NULL, _("NON"));
  gtk_widget_show (chayma_radiobutton_sup_rec);
  gtk_fixed_put (GTK_FIXED (fixed52), chayma_radiobutton_sup_rec, 272, 144);
  gtk_widget_set_size_request (chayma_radiobutton_sup_rec, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (chayma_radiobutton_sup_rec), chayma_radiobutton_sup_rec_group);
  chayma_radiobutton_sup_rec_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (chayma_radiobutton_sup_rec));

  chayma_radiobutton_sup_non = gtk_radio_button_new_with_mnemonic (NULL, _("OUI"));
  gtk_widget_show (chayma_radiobutton_sup_non);
  gtk_fixed_put (GTK_FIXED (fixed52), chayma_radiobutton_sup_non, 104, 144);
  gtk_widget_set_size_request (chayma_radiobutton_sup_non, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (chayma_radiobutton_sup_non), chayma_radiobutton_sup_rec_group);
  chayma_radiobutton_sup_rec_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (chayma_radiobutton_sup_non));

  label321 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\">ETES-VOUS SURE DE SUPPRIMER CETTE RECLAMATION</span></b>"));
  gtk_widget_show (label321);
  gtk_fixed_put (GTK_FIXED (fixed52), label321, 16, 32);
  gtk_widget_set_size_request (label321, 448, 80);
  gtk_label_set_use_markup (GTK_LABEL (label321), TRUE);

  chayma_button_conf_suprec = gtk_button_new ();
  gtk_widget_show (chayma_button_conf_suprec);
  gtk_fixed_put (GTK_FIXED (fixed52), chayma_button_conf_suprec, 160, 224);
  gtk_widget_set_size_request (chayma_button_conf_suprec, 136, 40);

  alignment107 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment107);
  gtk_container_add (GTK_CONTAINER (chayma_button_conf_suprec), alignment107);

  hbox107 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox107);
  gtk_container_add (GTK_CONTAINER (alignment107), hbox107);

  image160 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image160);
  gtk_box_pack_start (GTK_BOX (hbox107), image160, FALSE, FALSE, 0);

  label322 = gtk_label_new_with_mnemonic (_("<b><span color=\"green\">Confirmer</span></b>"));
  gtk_widget_show (label322);
  gtk_box_pack_start (GTK_BOX (hbox107), label322, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label322), TRUE);

  g_signal_connect ((gpointer) chayma_radiobutton_sup_rec, "toggled",
                    G_CALLBACK (on_chayma_radiobutton_sup_rec_toggled),
                    NULL);
  g_signal_connect ((gpointer) chayma_radiobutton_sup_non, "toggled",
                    G_CALLBACK (on_chayma_radiobutton_sup_non_toggled),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_conf_suprec, "clicked",
                    G_CALLBACK (on_chayma_button_conf_suprec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (chayma_window_suprec, chayma_window_suprec, "chayma_window_suprec");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, fixed52, "fixed52");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, chayma_radiobutton_sup_rec, "chayma_radiobutton_sup_rec");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, chayma_radiobutton_sup_non, "chayma_radiobutton_sup_non");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, label321, "label321");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, chayma_button_conf_suprec, "chayma_button_conf_suprec");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, alignment107, "alignment107");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, hbox107, "hbox107");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, image160, "image160");
  GLADE_HOOKUP_OBJECT (chayma_window_suprec, label322, "label322");

  return chayma_window_suprec;
}

GtkWidget*
create_window_chayma_stat_nb_rec (void)
{
  GtkWidget *window_chayma_stat_nb_rec;
  GtkWidget *fixed55;
  GtkWidget *image163;
  GtkWidget *chayma_entry_stat_rec;
  GtkWidget *label331;
  GtkWidget *label330;
  GtkWidget *chayma_treeview_stat_rec;
  GtkWidget *chayma_button_stat_ret_rec;
  GtkWidget *alignment109;
  GtkWidget *hbox109;
  GtkWidget *image164;
  GtkWidget *label333;
  GtkWidget *label329;
  GtkWidget *chayma_aff_stat_nb_rec;
  GtkWidget *alignment111;
  GtkWidget *hbox111;
  GtkWidget *image167;
  GtkWidget *label336;
  GtkWidget *chayma_label_aff_nb;

  window_chayma_stat_nb_rec = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_chayma_stat_nb_rec, 780, 650);
  gtk_window_set_title (GTK_WINDOW (window_chayma_stat_nb_rec), _("Nombre de reclamation"));

  fixed55 = gtk_fixed_new ();
  gtk_widget_show (fixed55);
  gtk_container_add (GTK_CONTAINER (window_chayma_stat_nb_rec), fixed55);
  gtk_widget_set_size_request (fixed55, 780, 650);

  image163 = create_pixmap (window_chayma_stat_nb_rec, "index.png");
  gtk_widget_show (image163);
  gtk_fixed_put (GTK_FIXED (fixed55), image163, 0, 0);
  gtk_widget_set_size_request (image163, 184, 136);

  chayma_entry_stat_rec = gtk_entry_new ();
  gtk_widget_show (chayma_entry_stat_rec);
  gtk_fixed_put (GTK_FIXED (fixed55), chayma_entry_stat_rec, 360, 264);
  gtk_widget_set_size_request (chayma_entry_stat_rec, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (chayma_entry_stat_rec), 8226);

  label331 = gtk_label_new_with_mnemonic (_("<b><span color=\"green\"> Entrez numero de list : </span></b>"));
  gtk_widget_show (label331);
  gtk_fixed_put (GTK_FIXED (fixed55), label331, 88, 248);
  gtk_widget_set_size_request (label331, 280, 56);
  gtk_label_set_use_markup (GTK_LABEL (label331), TRUE);

  label330 = gtk_label_new_with_mnemonic (_("<b><span color=\"green\"> Nombre totale de  Reclamation : </span></b>"));
  gtk_widget_show (label330);
  gtk_fixed_put (GTK_FIXED (fixed55), label330, 216, 208);
  gtk_widget_set_size_request (label330, 280, 32);
  gtk_label_set_use_markup (GTK_LABEL (label330), TRUE);

  chayma_treeview_stat_rec = gtk_tree_view_new ();
  gtk_widget_show (chayma_treeview_stat_rec);
  gtk_fixed_put (GTK_FIXED (fixed55), chayma_treeview_stat_rec, 216, 344);
  gtk_widget_set_size_request (chayma_treeview_stat_rec, 520, 184);

  chayma_button_stat_ret_rec = gtk_button_new ();
  gtk_widget_show (chayma_button_stat_ret_rec);
  gtk_fixed_put (GTK_FIXED (fixed55), chayma_button_stat_ret_rec, 32, 584);
  gtk_widget_set_size_request (chayma_button_stat_ret_rec, 160, 48);

  alignment109 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment109);
  gtk_container_add (GTK_CONTAINER (chayma_button_stat_ret_rec), alignment109);

  hbox109 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox109);
  gtk_container_add (GTK_CONTAINER (alignment109), hbox109);

  image164 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image164);
  gtk_box_pack_start (GTK_BOX (hbox109), image164, FALSE, FALSE, 0);

  label333 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Retour</span></b>"));
  gtk_widget_show (label333);
  gtk_box_pack_start (GTK_BOX (hbox109), label333, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label333), TRUE);

  label329 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\"> Nombre de  Reclamation</span></b>"));
  gtk_widget_show (label329);
  gtk_fixed_put (GTK_FIXED (fixed55), label329, 296, 80);
  gtk_widget_set_size_request (label329, 200, 40);
  gtk_label_set_use_markup (GTK_LABEL (label329), TRUE);

  chayma_aff_stat_nb_rec = gtk_button_new ();
  gtk_widget_show (chayma_aff_stat_nb_rec);
  gtk_fixed_put (GTK_FIXED (fixed55), chayma_aff_stat_nb_rec, 56, 344);
  gtk_widget_set_size_request (chayma_aff_stat_nb_rec, 120, 37);

  alignment111 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment111);
  gtk_container_add (GTK_CONTAINER (chayma_aff_stat_nb_rec), alignment111);

  hbox111 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox111);
  gtk_container_add (GTK_CONTAINER (alignment111), hbox111);

  image167 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image167);
  gtk_box_pack_start (GTK_BOX (hbox111), image167, FALSE, FALSE, 0);

  label336 = gtk_label_new_with_mnemonic (_("<b><span color=\"blue\"> Afficher</span></b>"));
  gtk_widget_show (label336);
  gtk_box_pack_start (GTK_BOX (hbox111), label336, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label336), TRUE);

  chayma_label_aff_nb = gtk_label_new ("");
  gtk_widget_show (chayma_label_aff_nb);
  gtk_fixed_put (GTK_FIXED (fixed55), chayma_label_aff_nb, 472, 192);
  gtk_widget_set_size_request (chayma_label_aff_nb, 176, 64);

  g_signal_connect ((gpointer) window_chayma_stat_nb_rec, "focus_in_event",
                    G_CALLBACK (on_window_chayma_stat_nb_rec_focus_in_event),
                    NULL);
  g_signal_connect ((gpointer) chayma_entry_stat_rec, "changed",
                    G_CALLBACK (on_chayma_entry_stat_rec_changed),
                    NULL);
  g_signal_connect ((gpointer) chayma_treeview_stat_rec, "row_activated",
                    G_CALLBACK (on_chayma_treeview_stat_rec_row_activated),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_stat_ret_rec, "clicked",
                    G_CALLBACK (on_chayma_button_stat_rec_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_stat_ret_rec, "clicked",
                    G_CALLBACK (on_chayma_button_stat_ret_rec_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_aff_stat_nb_rec, "clicked",
                    G_CALLBACK (on_chayma_aff_stat_nb_rec_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_chayma_stat_nb_rec, window_chayma_stat_nb_rec, "window_chayma_stat_nb_rec");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, fixed55, "fixed55");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, image163, "image163");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, chayma_entry_stat_rec, "chayma_entry_stat_rec");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, label331, "label331");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, label330, "label330");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, chayma_treeview_stat_rec, "chayma_treeview_stat_rec");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, chayma_button_stat_ret_rec, "chayma_button_stat_ret_rec");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, alignment109, "alignment109");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, hbox109, "hbox109");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, image164, "image164");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, label333, "label333");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, label329, "label329");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, chayma_aff_stat_nb_rec, "chayma_aff_stat_nb_rec");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, alignment111, "alignment111");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, hbox111, "hbox111");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, image167, "image167");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, label336, "label336");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_nb_rec, chayma_label_aff_nb, "chayma_label_aff_nb");

  return window_chayma_stat_nb_rec;
}

GtkWidget*
create_window_chayma_stat_gagnant (void)
{
  GtkWidget *window_chayma_stat_gagnant;
  GtkWidget *fixed54;
  GtkWidget *image165;
  GtkWidget *chayma_treeview_stat_gag;
  GtkWidget *label334;
  GtkWidget *chayma_button_aff_stat_gag;
  GtkWidget *alignment112;
  GtkWidget *hbox112;
  GtkWidget *image168;
  GtkWidget *label337;
  GtkWidget *chayma_button_stat_ret_nb_gag;
  GtkWidget *alignment110;
  GtkWidget *hbox110;
  GtkWidget *image166;
  GtkWidget *label335;

  window_chayma_stat_gagnant = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (window_chayma_stat_gagnant, 720, 585);
  gtk_window_set_title (GTK_WINDOW (window_chayma_stat_gagnant), _("Les conseillers gagnants"));

  fixed54 = gtk_fixed_new ();
  gtk_widget_show (fixed54);
  gtk_container_add (GTK_CONTAINER (window_chayma_stat_gagnant), fixed54);
  gtk_widget_set_size_request (fixed54, 720, 585);

  image165 = create_pixmap (window_chayma_stat_gagnant, "index.png");
  gtk_widget_show (image165);
  gtk_fixed_put (GTK_FIXED (fixed54), image165, 0, 0);
  gtk_widget_set_size_request (image165, 184, 136);

  chayma_treeview_stat_gag = gtk_tree_view_new ();
  gtk_widget_show (chayma_treeview_stat_gag);
  gtk_fixed_put (GTK_FIXED (fixed54), chayma_treeview_stat_gag, 200, 176);
  gtk_widget_set_size_request (chayma_treeview_stat_gag, 460, 184);

  label334 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\"> Les conseillers gagnants</span></b>"));
  gtk_widget_show (label334);
  gtk_fixed_put (GTK_FIXED (fixed54), label334, 248, 48);
  gtk_widget_set_size_request (label334, 208, 48);
  gtk_label_set_use_markup (GTK_LABEL (label334), TRUE);

  chayma_button_aff_stat_gag = gtk_button_new ();
  gtk_widget_show (chayma_button_aff_stat_gag);
  gtk_fixed_put (GTK_FIXED (fixed54), chayma_button_aff_stat_gag, 24, 184);
  gtk_widget_set_size_request (chayma_button_aff_stat_gag, 120, 37);

  alignment112 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment112);
  gtk_container_add (GTK_CONTAINER (chayma_button_aff_stat_gag), alignment112);

  hbox112 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox112);
  gtk_container_add (GTK_CONTAINER (alignment112), hbox112);

  image168 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image168);
  gtk_box_pack_start (GTK_BOX (hbox112), image168, FALSE, FALSE, 0);

  label337 = gtk_label_new_with_mnemonic (_("<b><span color=\"blue\"> Afficher</span></b>"));
  gtk_widget_show (label337);
  gtk_box_pack_start (GTK_BOX (hbox112), label337, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label337), TRUE);

  chayma_button_stat_ret_nb_gag = gtk_button_new ();
  gtk_widget_show (chayma_button_stat_ret_nb_gag);
  gtk_fixed_put (GTK_FIXED (fixed54), chayma_button_stat_ret_nb_gag, 32, 528);
  gtk_widget_set_size_request (chayma_button_stat_ret_nb_gag, 160, 48);

  alignment110 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment110);
  gtk_container_add (GTK_CONTAINER (chayma_button_stat_ret_nb_gag), alignment110);

  hbox110 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox110);
  gtk_container_add (GTK_CONTAINER (alignment110), hbox110);

  image166 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image166);
  gtk_box_pack_start (GTK_BOX (hbox110), image166, FALSE, FALSE, 0);

  label335 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\"> Retour</span></b>"));
  gtk_widget_show (label335);
  gtk_box_pack_start (GTK_BOX (hbox110), label335, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label335), TRUE);

  g_signal_connect ((gpointer) window_chayma_stat_gagnant, "focus_in_event",
                    G_CALLBACK (on_window_chayma_stat_gagnant_focus_in_event),
                    NULL);
  g_signal_connect ((gpointer) chayma_treeview_stat_gag, "row_activated",
                    G_CALLBACK (on_chayma_treeview_stat_gag_row_activated),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_aff_stat_gag, "clicked",
                    G_CALLBACK (on_chayma_button_aff_stat_gag_clicked),
                    NULL);
  g_signal_connect ((gpointer) chayma_button_stat_ret_nb_gag, "clicked",
                    G_CALLBACK (on_chayma_button_stat_ret_nb_gag_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_chayma_stat_gagnant, window_chayma_stat_gagnant, "window_chayma_stat_gagnant");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_gagnant, fixed54, "fixed54");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_gagnant, image165, "image165");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_gagnant, chayma_treeview_stat_gag, "chayma_treeview_stat_gag");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_gagnant, label334, "label334");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_gagnant, chayma_button_aff_stat_gag, "chayma_button_aff_stat_gag");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_gagnant, alignment112, "alignment112");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_gagnant, hbox112, "hbox112");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_gagnant, image168, "image168");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_gagnant, label337, "label337");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_gagnant, chayma_button_stat_ret_nb_gag, "chayma_button_stat_ret_nb_gag");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_gagnant, alignment110, "alignment110");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_gagnant, hbox110, "hbox110");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_gagnant, image166, "image166");
  GLADE_HOOKUP_OBJECT (window_chayma_stat_gagnant, label335, "label335");

  return window_chayma_stat_gagnant;
}

